
# This file is automatically generated, you probably don't want to edit this

GroupCoOccurrenceTNAOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "GroupCoOccurrenceTNAOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            buildModel_variables_long_action = NULL,
            buildModel_variables_long_actor = NULL,
            buildModel_variables_long_time = NULL,
            buildModel_variables_long_order = NULL,
            buildModel_variables_long_group = NULL,
            buildModel_scaling = "noScaling",
            buildModel_show_matrix = FALSE,
            buildModel_threshold = 900,
            buildModel_show_plot = TRUE,
            buildModel_plot_cut = 0.1,
            buildModel_plot_min_value = 0.05,
            buildModel_plot_edge_label_size = 1,
            buildModel_plot_node_size = 1,
            buildModel_plot_node_label_size = 1,
            buildModel_plot_layout = NULL,
            buildModel_show_histo = FALSE,
            buildModel_show_frequencies = FALSE,
            centrality_loops = FALSE,
            centrality_normalize = FALSE,
            centrality_show_table = FALSE,
            centrality_show_plot = FALSE,
            centrality_Betweenness = TRUE,
            centrality_BetweennessRSP = FALSE,
            centrality_Closeness = FALSE,
            centrality_ClosenessIn = FALSE,
            centrality_ClosenessOut = FALSE,
            centrality_Clustering = FALSE,
            centrality_Diffusion = FALSE,
            centrality_InStrength = TRUE,
            centrality_OutStrength = TRUE,
            community_methods = "spinglass",
            community_gamma = 1,
            community_show_plot = FALSE,
            community_show_table = FALSE,
            cliques_size = 2,
            cliques_threshold = 0,
            cliques_show_text = FALSE,
            cliques_show_plot = FALSE,
            cliques_plot_cut = 0.1,
            cliques_plot_min_value = 0,
            cliques_plot_edge_label_size = 1,
            cliques_plot_node_size = 1,
            cliques_plot_node_label_size = 1,
            cliques_plot_layout = "circle",
            bootstrap_iteration = 1000,
            bootstrap_level = 0.05,
            bootstrap_method = "stability",
            bootstrap_range_low = 0.75,
            bootstrap_range_up = 1.25,
            bootstrap_threshold = 0.1,
            bootstrap_show_table = FALSE,
            bootstrap_table_max_rows = 20,
            bootstrap_table_show_all = FALSE,
            bootstrap_table_significant_only = FALSE,
            bootstrap_show_plot = FALSE,
            bootstrap_plot_cut = 0.1,
            bootstrap_plot_min_value = 0.05,
            bootstrap_plot_edge_label_size = 1,
            bootstrap_plot_node_size = 1,
            bootstrap_plot_node_label_size = 1,
            bootstrap_plot_layout = NULL,
            permutation_show_text = FALSE,
            permutation_show_plot = FALSE,
            permutation_iter = 1000,
            permutation_paired = FALSE,
            permutation_level = 0.05,
            permutation_table_max_rows = 20,
            permutation_table_show_all = FALSE,
            compare_show_summary = FALSE,
            compare_show_network = FALSE,
            compare_show_plot = FALSE,
            compare_group_i = NULL,
            compare_group_j = NULL,
            compare_scaling = "none",
            compare_plot_type = "heatmap",
            compare_show_network_diff_plot = FALSE,
            compare_network_diff_plot_cut = 0.1,
            compare_network_diff_plot_min_value = 0.05,
            compare_network_diff_plot_edge_label_size = 1,
            compare_network_diff_plot_node_size = 1,
            compare_network_diff_plot_node_label_size = 1,
            compare_network_diff_plot_layout = "circle", ...) {

            super$initialize(
                package="JTNA",
                name="GroupCoOccurrenceTNA",
                requiresData=TRUE,
                ...)

            private$..buildModel_variables_long_action <- jmvcore::OptionVariable$new(
                "buildModel_variables_long_action",
                buildModel_variables_long_action)
            private$..buildModel_variables_long_actor <- jmvcore::OptionVariable$new(
                "buildModel_variables_long_actor",
                buildModel_variables_long_actor)
            private$..buildModel_variables_long_time <- jmvcore::OptionVariable$new(
                "buildModel_variables_long_time",
                buildModel_variables_long_time)
            private$..buildModel_variables_long_order <- jmvcore::OptionVariable$new(
                "buildModel_variables_long_order",
                buildModel_variables_long_order)
            private$..buildModel_variables_long_group <- jmvcore::OptionVariable$new(
                "buildModel_variables_long_group",
                buildModel_variables_long_group)
            private$..buildModel_scaling <- jmvcore::OptionList$new(
                "buildModel_scaling",
                buildModel_scaling,
                options=list(
                    "noScaling",
                    "minmax",
                    "max",
                    "rank"),
                default="noScaling")
            private$..buildModel_show_matrix <- jmvcore::OptionBool$new(
                "buildModel_show_matrix",
                buildModel_show_matrix,
                default=FALSE)
            private$..buildModel_threshold <- jmvcore::OptionInteger$new(
                "buildModel_threshold",
                buildModel_threshold,
                default=900)
            private$..buildModel_show_plot <- jmvcore::OptionBool$new(
                "buildModel_show_plot",
                buildModel_show_plot,
                default=TRUE)
            private$..buildModel_plot_cut <- jmvcore::OptionNumber$new(
                "buildModel_plot_cut",
                buildModel_plot_cut,
                default=0.1,
                min=0,
                max=1)
            private$..buildModel_plot_min_value <- jmvcore::OptionNumber$new(
                "buildModel_plot_min_value",
                buildModel_plot_min_value,
                default=0.05,
                min=0,
                max=1)
            private$..buildModel_plot_edge_label_size <- jmvcore::OptionNumber$new(
                "buildModel_plot_edge_label_size",
                buildModel_plot_edge_label_size,
                default=1,
                min=0,
                max=10)
            private$..buildModel_plot_node_size <- jmvcore::OptionNumber$new(
                "buildModel_plot_node_size",
                buildModel_plot_node_size,
                default=1,
                min=0,
                max=2)
            private$..buildModel_plot_node_label_size <- jmvcore::OptionNumber$new(
                "buildModel_plot_node_label_size",
                buildModel_plot_node_label_size,
                default=1,
                min=0,
                max=10)
            private$..buildModel_plot_layout <- jmvcore::OptionList$new(
                "buildModel_plot_layout",
                buildModel_plot_layout,
                options=list(
                    "circle",
                    "spring",
                    "layout_with_kk",
                    "layout_with_graphopt",
                    "layout_with_gem",
                    "layout_with_drl",
                    "layout_as_star",
                    "layout_on_grid",
                    "layout_nicely",
                    "layout_with_fr",
                    "layout_with_dh",
                    "layout_with_lgl",
                    "layout_with_sugiyama",
                    "layout_randomly"))
            private$..buildModel_show_histo <- jmvcore::OptionBool$new(
                "buildModel_show_histo",
                buildModel_show_histo,
                default=FALSE)
            private$..buildModel_show_frequencies <- jmvcore::OptionBool$new(
                "buildModel_show_frequencies",
                buildModel_show_frequencies,
                default=FALSE)
            private$..centrality_loops <- jmvcore::OptionBool$new(
                "centrality_loops",
                centrality_loops,
                default=FALSE)
            private$..centrality_normalize <- jmvcore::OptionBool$new(
                "centrality_normalize",
                centrality_normalize,
                default=FALSE)
            private$..centrality_show_table <- jmvcore::OptionBool$new(
                "centrality_show_table",
                centrality_show_table,
                default=FALSE)
            private$..centrality_show_plot <- jmvcore::OptionBool$new(
                "centrality_show_plot",
                centrality_show_plot,
                default=FALSE)
            private$..centrality_Betweenness <- jmvcore::OptionBool$new(
                "centrality_Betweenness",
                centrality_Betweenness,
                default=TRUE)
            private$..centrality_BetweennessRSP <- jmvcore::OptionBool$new(
                "centrality_BetweennessRSP",
                centrality_BetweennessRSP,
                default=FALSE)
            private$..centrality_Closeness <- jmvcore::OptionBool$new(
                "centrality_Closeness",
                centrality_Closeness,
                default=FALSE)
            private$..centrality_ClosenessIn <- jmvcore::OptionBool$new(
                "centrality_ClosenessIn",
                centrality_ClosenessIn,
                default=FALSE)
            private$..centrality_ClosenessOut <- jmvcore::OptionBool$new(
                "centrality_ClosenessOut",
                centrality_ClosenessOut,
                default=FALSE)
            private$..centrality_Clustering <- jmvcore::OptionBool$new(
                "centrality_Clustering",
                centrality_Clustering,
                default=FALSE)
            private$..centrality_Diffusion <- jmvcore::OptionBool$new(
                "centrality_Diffusion",
                centrality_Diffusion,
                default=FALSE)
            private$..centrality_InStrength <- jmvcore::OptionBool$new(
                "centrality_InStrength",
                centrality_InStrength,
                default=TRUE)
            private$..centrality_OutStrength <- jmvcore::OptionBool$new(
                "centrality_OutStrength",
                centrality_OutStrength,
                default=TRUE)
            private$..community_methods <- jmvcore::OptionList$new(
                "community_methods",
                community_methods,
                default="spinglass",
                options=list(
                    "spinglass",
                    "walktrap",
                    "fast_greedy",
                    "label_prop",
                    "infomap",
                    "edge_betweenness",
                    "leading_eigen"))
            private$..community_gamma <- jmvcore::OptionInteger$new(
                "community_gamma",
                community_gamma,
                default=1,
                min=0,
                max=100)
            private$..community_show_plot <- jmvcore::OptionBool$new(
                "community_show_plot",
                community_show_plot,
                default=FALSE)
            private$..community_show_table <- jmvcore::OptionBool$new(
                "community_show_table",
                community_show_table,
                default=FALSE)
            private$..cliques_size <- jmvcore::OptionInteger$new(
                "cliques_size",
                cliques_size,
                default=2,
                min=2,
                max=10)
            private$..cliques_threshold <- jmvcore::OptionNumber$new(
                "cliques_threshold",
                cliques_threshold,
                default=0,
                min=0,
                max=1)
            private$..cliques_show_text <- jmvcore::OptionBool$new(
                "cliques_show_text",
                cliques_show_text,
                default=FALSE)
            private$..cliques_show_plot <- jmvcore::OptionBool$new(
                "cliques_show_plot",
                cliques_show_plot,
                default=FALSE)
            private$..cliques_plot_cut <- jmvcore::OptionNumber$new(
                "cliques_plot_cut",
                cliques_plot_cut,
                default=0.1,
                min=0,
                max=1)
            private$..cliques_plot_min_value <- jmvcore::OptionNumber$new(
                "cliques_plot_min_value",
                cliques_plot_min_value,
                default=0,
                min=0,
                max=1)
            private$..cliques_plot_edge_label_size <- jmvcore::OptionNumber$new(
                "cliques_plot_edge_label_size",
                cliques_plot_edge_label_size,
                default=1,
                min=0,
                max=10)
            private$..cliques_plot_node_size <- jmvcore::OptionNumber$new(
                "cliques_plot_node_size",
                cliques_plot_node_size,
                default=1,
                min=0,
                max=2)
            private$..cliques_plot_node_label_size <- jmvcore::OptionNumber$new(
                "cliques_plot_node_label_size",
                cliques_plot_node_label_size,
                default=1,
                min=0,
                max=10)
            private$..cliques_plot_layout <- jmvcore::OptionList$new(
                "cliques_plot_layout",
                cliques_plot_layout,
                default="circle",
                options=list(
                    "circle",
                    "spring",
                    "layout_with_kk",
                    "layout_with_graphopt",
                    "layout_with_gem",
                    "layout_with_drl",
                    "layout_as_star",
                    "layout_on_grid",
                    "layout_nicely",
                    "layout_with_fr",
                    "layout_with_dh",
                    "layout_with_lgl",
                    "layout_with_sugiyama",
                    "layout_randomly"))
            private$..bootstrap_iteration <- jmvcore::OptionInteger$new(
                "bootstrap_iteration",
                bootstrap_iteration,
                default=1000,
                min=0,
                max=10000)
            private$..bootstrap_level <- jmvcore::OptionNumber$new(
                "bootstrap_level",
                bootstrap_level,
                default=0.05,
                min=0,
                max=1)
            private$..bootstrap_method <- jmvcore::OptionList$new(
                "bootstrap_method",
                bootstrap_method,
                default="stability",
                options=list(
                    "stability",
                    "threshold"))
            private$..bootstrap_range_low <- jmvcore::OptionNumber$new(
                "bootstrap_range_low",
                bootstrap_range_low,
                default=0.75,
                min=0,
                max=10)
            private$..bootstrap_range_up <- jmvcore::OptionNumber$new(
                "bootstrap_range_up",
                bootstrap_range_up,
                default=1.25,
                min=0,
                max=10)
            private$..bootstrap_threshold <- jmvcore::OptionNumber$new(
                "bootstrap_threshold",
                bootstrap_threshold,
                default=0.1,
                min=0,
                max=1)
            private$..bootstrap_show_table <- jmvcore::OptionBool$new(
                "bootstrap_show_table",
                bootstrap_show_table,
                default=FALSE)
            private$..bootstrap_table_max_rows <- jmvcore::OptionInteger$new(
                "bootstrap_table_max_rows",
                bootstrap_table_max_rows,
                default=20,
                min=1,
                max=1000)
            private$..bootstrap_table_show_all <- jmvcore::OptionBool$new(
                "bootstrap_table_show_all",
                bootstrap_table_show_all,
                default=FALSE)
            private$..bootstrap_table_significant_only <- jmvcore::OptionBool$new(
                "bootstrap_table_significant_only",
                bootstrap_table_significant_only,
                default=FALSE)
            private$..bootstrap_show_plot <- jmvcore::OptionBool$new(
                "bootstrap_show_plot",
                bootstrap_show_plot,
                default=FALSE)
            private$..bootstrap_plot_cut <- jmvcore::OptionNumber$new(
                "bootstrap_plot_cut",
                bootstrap_plot_cut,
                default=0.1,
                min=0,
                max=1)
            private$..bootstrap_plot_min_value <- jmvcore::OptionNumber$new(
                "bootstrap_plot_min_value",
                bootstrap_plot_min_value,
                default=0.05,
                min=0,
                max=1)
            private$..bootstrap_plot_edge_label_size <- jmvcore::OptionNumber$new(
                "bootstrap_plot_edge_label_size",
                bootstrap_plot_edge_label_size,
                default=1,
                min=0,
                max=10)
            private$..bootstrap_plot_node_size <- jmvcore::OptionNumber$new(
                "bootstrap_plot_node_size",
                bootstrap_plot_node_size,
                default=1,
                min=0,
                max=2)
            private$..bootstrap_plot_node_label_size <- jmvcore::OptionNumber$new(
                "bootstrap_plot_node_label_size",
                bootstrap_plot_node_label_size,
                default=1,
                min=0,
                max=10)
            private$..bootstrap_plot_layout <- jmvcore::OptionList$new(
                "bootstrap_plot_layout",
                bootstrap_plot_layout,
                options=list(
                    "circle",
                    "spring",
                    "layout_with_kk",
                    "layout_with_graphopt",
                    "layout_with_gem",
                    "layout_with_drl",
                    "layout_as_star",
                    "layout_on_grid",
                    "layout_nicely",
                    "layout_with_fr",
                    "layout_with_dh",
                    "layout_with_lgl",
                    "layout_with_sugiyama",
                    "layout_randomly"))
            private$..permutation_show_text <- jmvcore::OptionBool$new(
                "permutation_show_text",
                permutation_show_text,
                default=FALSE)
            private$..permutation_show_plot <- jmvcore::OptionBool$new(
                "permutation_show_plot",
                permutation_show_plot,
                default=FALSE)
            private$..permutation_iter <- jmvcore::OptionInteger$new(
                "permutation_iter",
                permutation_iter,
                default=1000,
                min=1)
            private$..permutation_paired <- jmvcore::OptionBool$new(
                "permutation_paired",
                permutation_paired,
                default=FALSE)
            private$..permutation_level <- jmvcore::OptionNumber$new(
                "permutation_level",
                permutation_level,
                default=0.05,
                min=0,
                max=1)
            private$..permutation_table_max_rows <- jmvcore::OptionInteger$new(
                "permutation_table_max_rows",
                permutation_table_max_rows,
                default=20,
                min=1,
                max=1000)
            private$..permutation_table_show_all <- jmvcore::OptionBool$new(
                "permutation_table_show_all",
                permutation_table_show_all,
                default=FALSE)
            private$..compare_show_summary <- jmvcore::OptionBool$new(
                "compare_show_summary",
                compare_show_summary,
                default=FALSE)
            private$..compare_show_network <- jmvcore::OptionBool$new(
                "compare_show_network",
                compare_show_network,
                default=FALSE)
            private$..compare_show_plot <- jmvcore::OptionBool$new(
                "compare_show_plot",
                compare_show_plot,
                default=FALSE)
            private$..compare_group_i <- jmvcore::OptionLevel$new(
                "compare_group_i",
                compare_group_i,
                variable="(buildModel_variables_long_group)")
            private$..compare_group_j <- jmvcore::OptionLevel$new(
                "compare_group_j",
                compare_group_j,
                variable="(buildModel_variables_long_group)")
            private$..compare_scaling <- jmvcore::OptionList$new(
                "compare_scaling",
                compare_scaling,
                default="none",
                options=list(
                    "none",
                    "minmax",
                    "max",
                    "rank"))
            private$..compare_plot_type <- jmvcore::OptionList$new(
                "compare_plot_type",
                compare_plot_type,
                default="heatmap",
                options=list(
                    "heatmap",
                    "scatterplot",
                    "weight_density"))
            private$..compare_show_network_diff_plot <- jmvcore::OptionBool$new(
                "compare_show_network_diff_plot",
                compare_show_network_diff_plot,
                default=FALSE)
            private$..compare_network_diff_plot_cut <- jmvcore::OptionNumber$new(
                "compare_network_diff_plot_cut",
                compare_network_diff_plot_cut,
                default=0.1,
                min=0,
                max=1)
            private$..compare_network_diff_plot_min_value <- jmvcore::OptionNumber$new(
                "compare_network_diff_plot_min_value",
                compare_network_diff_plot_min_value,
                default=0.05,
                min=0,
                max=1)
            private$..compare_network_diff_plot_edge_label_size <- jmvcore::OptionNumber$new(
                "compare_network_diff_plot_edge_label_size",
                compare_network_diff_plot_edge_label_size,
                default=1,
                min=0,
                max=10)
            private$..compare_network_diff_plot_node_size <- jmvcore::OptionNumber$new(
                "compare_network_diff_plot_node_size",
                compare_network_diff_plot_node_size,
                default=1,
                min=0,
                max=2)
            private$..compare_network_diff_plot_node_label_size <- jmvcore::OptionNumber$new(
                "compare_network_diff_plot_node_label_size",
                compare_network_diff_plot_node_label_size,
                default=1,
                min=0,
                max=10)
            private$..compare_network_diff_plot_layout <- jmvcore::OptionList$new(
                "compare_network_diff_plot_layout",
                compare_network_diff_plot_layout,
                default="circle",
                options=list(
                    "circle",
                    "spring",
                    "layout_with_fr"))

            self$.addOption(private$..buildModel_variables_long_action)
            self$.addOption(private$..buildModel_variables_long_actor)
            self$.addOption(private$..buildModel_variables_long_time)
            self$.addOption(private$..buildModel_variables_long_order)
            self$.addOption(private$..buildModel_variables_long_group)
            self$.addOption(private$..buildModel_scaling)
            self$.addOption(private$..buildModel_show_matrix)
            self$.addOption(private$..buildModel_threshold)
            self$.addOption(private$..buildModel_show_plot)
            self$.addOption(private$..buildModel_plot_cut)
            self$.addOption(private$..buildModel_plot_min_value)
            self$.addOption(private$..buildModel_plot_edge_label_size)
            self$.addOption(private$..buildModel_plot_node_size)
            self$.addOption(private$..buildModel_plot_node_label_size)
            self$.addOption(private$..buildModel_plot_layout)
            self$.addOption(private$..buildModel_show_histo)
            self$.addOption(private$..buildModel_show_frequencies)
            self$.addOption(private$..centrality_loops)
            self$.addOption(private$..centrality_normalize)
            self$.addOption(private$..centrality_show_table)
            self$.addOption(private$..centrality_show_plot)
            self$.addOption(private$..centrality_Betweenness)
            self$.addOption(private$..centrality_BetweennessRSP)
            self$.addOption(private$..centrality_Closeness)
            self$.addOption(private$..centrality_ClosenessIn)
            self$.addOption(private$..centrality_ClosenessOut)
            self$.addOption(private$..centrality_Clustering)
            self$.addOption(private$..centrality_Diffusion)
            self$.addOption(private$..centrality_InStrength)
            self$.addOption(private$..centrality_OutStrength)
            self$.addOption(private$..community_methods)
            self$.addOption(private$..community_gamma)
            self$.addOption(private$..community_show_plot)
            self$.addOption(private$..community_show_table)
            self$.addOption(private$..cliques_size)
            self$.addOption(private$..cliques_threshold)
            self$.addOption(private$..cliques_show_text)
            self$.addOption(private$..cliques_show_plot)
            self$.addOption(private$..cliques_plot_cut)
            self$.addOption(private$..cliques_plot_min_value)
            self$.addOption(private$..cliques_plot_edge_label_size)
            self$.addOption(private$..cliques_plot_node_size)
            self$.addOption(private$..cliques_plot_node_label_size)
            self$.addOption(private$..cliques_plot_layout)
            self$.addOption(private$..bootstrap_iteration)
            self$.addOption(private$..bootstrap_level)
            self$.addOption(private$..bootstrap_method)
            self$.addOption(private$..bootstrap_range_low)
            self$.addOption(private$..bootstrap_range_up)
            self$.addOption(private$..bootstrap_threshold)
            self$.addOption(private$..bootstrap_show_table)
            self$.addOption(private$..bootstrap_table_max_rows)
            self$.addOption(private$..bootstrap_table_show_all)
            self$.addOption(private$..bootstrap_table_significant_only)
            self$.addOption(private$..bootstrap_show_plot)
            self$.addOption(private$..bootstrap_plot_cut)
            self$.addOption(private$..bootstrap_plot_min_value)
            self$.addOption(private$..bootstrap_plot_edge_label_size)
            self$.addOption(private$..bootstrap_plot_node_size)
            self$.addOption(private$..bootstrap_plot_node_label_size)
            self$.addOption(private$..bootstrap_plot_layout)
            self$.addOption(private$..permutation_show_text)
            self$.addOption(private$..permutation_show_plot)
            self$.addOption(private$..permutation_iter)
            self$.addOption(private$..permutation_paired)
            self$.addOption(private$..permutation_level)
            self$.addOption(private$..permutation_table_max_rows)
            self$.addOption(private$..permutation_table_show_all)
            self$.addOption(private$..compare_show_summary)
            self$.addOption(private$..compare_show_network)
            self$.addOption(private$..compare_show_plot)
            self$.addOption(private$..compare_group_i)
            self$.addOption(private$..compare_group_j)
            self$.addOption(private$..compare_scaling)
            self$.addOption(private$..compare_plot_type)
            self$.addOption(private$..compare_show_network_diff_plot)
            self$.addOption(private$..compare_network_diff_plot_cut)
            self$.addOption(private$..compare_network_diff_plot_min_value)
            self$.addOption(private$..compare_network_diff_plot_edge_label_size)
            self$.addOption(private$..compare_network_diff_plot_node_size)
            self$.addOption(private$..compare_network_diff_plot_node_label_size)
            self$.addOption(private$..compare_network_diff_plot_layout)
        }),
    active = list(
        buildModel_variables_long_action = function() private$..buildModel_variables_long_action$value,
        buildModel_variables_long_actor = function() private$..buildModel_variables_long_actor$value,
        buildModel_variables_long_time = function() private$..buildModel_variables_long_time$value,
        buildModel_variables_long_order = function() private$..buildModel_variables_long_order$value,
        buildModel_variables_long_group = function() private$..buildModel_variables_long_group$value,
        buildModel_scaling = function() private$..buildModel_scaling$value,
        buildModel_show_matrix = function() private$..buildModel_show_matrix$value,
        buildModel_threshold = function() private$..buildModel_threshold$value,
        buildModel_show_plot = function() private$..buildModel_show_plot$value,
        buildModel_plot_cut = function() private$..buildModel_plot_cut$value,
        buildModel_plot_min_value = function() private$..buildModel_plot_min_value$value,
        buildModel_plot_edge_label_size = function() private$..buildModel_plot_edge_label_size$value,
        buildModel_plot_node_size = function() private$..buildModel_plot_node_size$value,
        buildModel_plot_node_label_size = function() private$..buildModel_plot_node_label_size$value,
        buildModel_plot_layout = function() private$..buildModel_plot_layout$value,
        buildModel_show_histo = function() private$..buildModel_show_histo$value,
        buildModel_show_frequencies = function() private$..buildModel_show_frequencies$value,
        centrality_loops = function() private$..centrality_loops$value,
        centrality_normalize = function() private$..centrality_normalize$value,
        centrality_show_table = function() private$..centrality_show_table$value,
        centrality_show_plot = function() private$..centrality_show_plot$value,
        centrality_Betweenness = function() private$..centrality_Betweenness$value,
        centrality_BetweennessRSP = function() private$..centrality_BetweennessRSP$value,
        centrality_Closeness = function() private$..centrality_Closeness$value,
        centrality_ClosenessIn = function() private$..centrality_ClosenessIn$value,
        centrality_ClosenessOut = function() private$..centrality_ClosenessOut$value,
        centrality_Clustering = function() private$..centrality_Clustering$value,
        centrality_Diffusion = function() private$..centrality_Diffusion$value,
        centrality_InStrength = function() private$..centrality_InStrength$value,
        centrality_OutStrength = function() private$..centrality_OutStrength$value,
        community_methods = function() private$..community_methods$value,
        community_gamma = function() private$..community_gamma$value,
        community_show_plot = function() private$..community_show_plot$value,
        community_show_table = function() private$..community_show_table$value,
        cliques_size = function() private$..cliques_size$value,
        cliques_threshold = function() private$..cliques_threshold$value,
        cliques_show_text = function() private$..cliques_show_text$value,
        cliques_show_plot = function() private$..cliques_show_plot$value,
        cliques_plot_cut = function() private$..cliques_plot_cut$value,
        cliques_plot_min_value = function() private$..cliques_plot_min_value$value,
        cliques_plot_edge_label_size = function() private$..cliques_plot_edge_label_size$value,
        cliques_plot_node_size = function() private$..cliques_plot_node_size$value,
        cliques_plot_node_label_size = function() private$..cliques_plot_node_label_size$value,
        cliques_plot_layout = function() private$..cliques_plot_layout$value,
        bootstrap_iteration = function() private$..bootstrap_iteration$value,
        bootstrap_level = function() private$..bootstrap_level$value,
        bootstrap_method = function() private$..bootstrap_method$value,
        bootstrap_range_low = function() private$..bootstrap_range_low$value,
        bootstrap_range_up = function() private$..bootstrap_range_up$value,
        bootstrap_threshold = function() private$..bootstrap_threshold$value,
        bootstrap_show_table = function() private$..bootstrap_show_table$value,
        bootstrap_table_max_rows = function() private$..bootstrap_table_max_rows$value,
        bootstrap_table_show_all = function() private$..bootstrap_table_show_all$value,
        bootstrap_table_significant_only = function() private$..bootstrap_table_significant_only$value,
        bootstrap_show_plot = function() private$..bootstrap_show_plot$value,
        bootstrap_plot_cut = function() private$..bootstrap_plot_cut$value,
        bootstrap_plot_min_value = function() private$..bootstrap_plot_min_value$value,
        bootstrap_plot_edge_label_size = function() private$..bootstrap_plot_edge_label_size$value,
        bootstrap_plot_node_size = function() private$..bootstrap_plot_node_size$value,
        bootstrap_plot_node_label_size = function() private$..bootstrap_plot_node_label_size$value,
        bootstrap_plot_layout = function() private$..bootstrap_plot_layout$value,
        permutation_show_text = function() private$..permutation_show_text$value,
        permutation_show_plot = function() private$..permutation_show_plot$value,
        permutation_iter = function() private$..permutation_iter$value,
        permutation_paired = function() private$..permutation_paired$value,
        permutation_level = function() private$..permutation_level$value,
        permutation_table_max_rows = function() private$..permutation_table_max_rows$value,
        permutation_table_show_all = function() private$..permutation_table_show_all$value,
        compare_show_summary = function() private$..compare_show_summary$value,
        compare_show_network = function() private$..compare_show_network$value,
        compare_show_plot = function() private$..compare_show_plot$value,
        compare_group_i = function() private$..compare_group_i$value,
        compare_group_j = function() private$..compare_group_j$value,
        compare_scaling = function() private$..compare_scaling$value,
        compare_plot_type = function() private$..compare_plot_type$value,
        compare_show_network_diff_plot = function() private$..compare_show_network_diff_plot$value,
        compare_network_diff_plot_cut = function() private$..compare_network_diff_plot_cut$value,
        compare_network_diff_plot_min_value = function() private$..compare_network_diff_plot_min_value$value,
        compare_network_diff_plot_edge_label_size = function() private$..compare_network_diff_plot_edge_label_size$value,
        compare_network_diff_plot_node_size = function() private$..compare_network_diff_plot_node_size$value,
        compare_network_diff_plot_node_label_size = function() private$..compare_network_diff_plot_node_label_size$value,
        compare_network_diff_plot_layout = function() private$..compare_network_diff_plot_layout$value),
    private = list(
        ..buildModel_variables_long_action = NA,
        ..buildModel_variables_long_actor = NA,
        ..buildModel_variables_long_time = NA,
        ..buildModel_variables_long_order = NA,
        ..buildModel_variables_long_group = NA,
        ..buildModel_scaling = NA,
        ..buildModel_show_matrix = NA,
        ..buildModel_threshold = NA,
        ..buildModel_show_plot = NA,
        ..buildModel_plot_cut = NA,
        ..buildModel_plot_min_value = NA,
        ..buildModel_plot_edge_label_size = NA,
        ..buildModel_plot_node_size = NA,
        ..buildModel_plot_node_label_size = NA,
        ..buildModel_plot_layout = NA,
        ..buildModel_show_histo = NA,
        ..buildModel_show_frequencies = NA,
        ..centrality_loops = NA,
        ..centrality_normalize = NA,
        ..centrality_show_table = NA,
        ..centrality_show_plot = NA,
        ..centrality_Betweenness = NA,
        ..centrality_BetweennessRSP = NA,
        ..centrality_Closeness = NA,
        ..centrality_ClosenessIn = NA,
        ..centrality_ClosenessOut = NA,
        ..centrality_Clustering = NA,
        ..centrality_Diffusion = NA,
        ..centrality_InStrength = NA,
        ..centrality_OutStrength = NA,
        ..community_methods = NA,
        ..community_gamma = NA,
        ..community_show_plot = NA,
        ..community_show_table = NA,
        ..cliques_size = NA,
        ..cliques_threshold = NA,
        ..cliques_show_text = NA,
        ..cliques_show_plot = NA,
        ..cliques_plot_cut = NA,
        ..cliques_plot_min_value = NA,
        ..cliques_plot_edge_label_size = NA,
        ..cliques_plot_node_size = NA,
        ..cliques_plot_node_label_size = NA,
        ..cliques_plot_layout = NA,
        ..bootstrap_iteration = NA,
        ..bootstrap_level = NA,
        ..bootstrap_method = NA,
        ..bootstrap_range_low = NA,
        ..bootstrap_range_up = NA,
        ..bootstrap_threshold = NA,
        ..bootstrap_show_table = NA,
        ..bootstrap_table_max_rows = NA,
        ..bootstrap_table_show_all = NA,
        ..bootstrap_table_significant_only = NA,
        ..bootstrap_show_plot = NA,
        ..bootstrap_plot_cut = NA,
        ..bootstrap_plot_min_value = NA,
        ..bootstrap_plot_edge_label_size = NA,
        ..bootstrap_plot_node_size = NA,
        ..bootstrap_plot_node_label_size = NA,
        ..bootstrap_plot_layout = NA,
        ..permutation_show_text = NA,
        ..permutation_show_plot = NA,
        ..permutation_iter = NA,
        ..permutation_paired = NA,
        ..permutation_level = NA,
        ..permutation_table_max_rows = NA,
        ..permutation_table_show_all = NA,
        ..compare_show_summary = NA,
        ..compare_show_network = NA,
        ..compare_show_plot = NA,
        ..compare_group_i = NA,
        ..compare_group_j = NA,
        ..compare_scaling = NA,
        ..compare_plot_type = NA,
        ..compare_show_network_diff_plot = NA,
        ..compare_network_diff_plot_cut = NA,
        ..compare_network_diff_plot_min_value = NA,
        ..compare_network_diff_plot_edge_label_size = NA,
        ..compare_network_diff_plot_node_size = NA,
        ..compare_network_diff_plot_node_label_size = NA,
        ..compare_network_diff_plot_layout = NA)
)

GroupCoOccurrenceTNAResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "GroupCoOccurrenceTNAResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        errorText = function() private$.items[["errorText"]],
        tnaTitle = function() private$.items[["tnaTitle"]],
        buildModelTitle = function() private$.items[["buildModelTitle"]],
        buildModelContent = function() private$.items[["buildModelContent"]],
        buildModel_plot = function() private$.items[["buildModel_plot"]],
        buildModel_histo = function() private$.items[["buildModel_histo"]],
        buildModel_frequencies = function() private$.items[["buildModel_frequencies"]],
        centralityTitle = function() private$.items[["centralityTitle"]],
        centralityContent = function() private$.items[["centralityContent"]],
        centralityTable = function() private$.items[["centralityTable"]],
        centrality_plot = function() private$.items[["centrality_plot"]],
        communityTitle = function() private$.items[["communityTitle"]],
        communityErrorText = function() private$.items[["communityErrorText"]],
        communityContent = function() private$.items[["communityContent"]],
        community_plot = function() private$.items[["community_plot"]],
        communityTable = function() private$.items[["communityTable"]],
        cliquesTitle = function() private$.items[["cliquesTitle"]],
        cliquesContent = function() private$.items[["cliquesContent"]],
        cliques_multiple_plot = function() private$.items[["cliques_multiple_plot"]],
        bootstrapTitle = function() private$.items[["bootstrapTitle"]],
        bootstrapTable = function() private$.items[["bootstrapTable"]],
        bootstrap_plot = function() private$.items[["bootstrap_plot"]],
        permutationTitle = function() private$.items[["permutationTitle"]],
        permutationContent = function() private$.items[["permutationContent"]],
        permutation_plot = function() private$.items[["permutation_plot"]],
        compare_network_diff_plot = function() private$.items[["compare_network_diff_plot"]],
        compareInstructions = function() private$.items[["compareInstructions"]],
        compareTitle = function() private$.items[["compareTitle"]],
        compare_plot = function() private$.items[["compare_plot"]],
        compareSummaryTable = function() private$.items[["compareSummaryTable"]],
        compareNetworkTable = function() private$.items[["compareNetworkTable"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Group Co-occurrence Network Analysis",
                refs=list(
                    "JTNA",
                    "TNA",
                    "TNALAK"))
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="errorText",
                title="Error",
                visible=FALSE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="tnaTitle",
                title="Group Co-occurrence Network Analysis",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="buildModelTitle",
                title="Model",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="buildModelContent",
                visible=FALSE,
                clearWith=list(
                    "buildModel_variables_long_actor",
                    "buildModel_variables_long_time",
                    "buildModel_variables_long_action",
                    "buildModel_variables_long_order",
                    "buildModel_variables_long_group",
                    "buildModel_scaling",
                    "buildModel_threshold")))
            self$add(jmvcore::Image$new(
                options=options,
                name="buildModel_plot",
                width=1000,
                height=800,
                visible=FALSE,
                renderFun=".showBuildModelPlot",
                clearWith=list(
                    "buildModel_variables_long_actor",
                    "buildModel_variables_long_time",
                    "buildModel_variables_long_action",
                    "buildModel_variables_long_order",
                    "buildModel_variables_long_group",
                    "buildModel_scaling",
                    "buildModel_threshold",
                    "buildModel_plot_cut",
                    "buildModel_plot_min_value",
                    "buildModel_plot_edge_label_size",
                    "buildModel_plot_node_size",
                    "buildModel_plot_node_label_size",
                    "buildModel_plot_layout")))
            self$add(jmvcore::Image$new(
                options=options,
                name="buildModel_histo",
                width=1000,
                height=800,
                visible=FALSE,
                renderFun=".showBuildModelHisto",
                clearWith=list(
                    "buildModel_variables_long_actor",
                    "buildModel_variables_long_time",
                    "buildModel_variables_long_action",
                    "buildModel_variables_long_order",
                    "buildModel_variables_long_group",
                    "buildModel_scaling",
                    "buildModel_threshold")))
            self$add(jmvcore::Image$new(
                options=options,
                name="buildModel_frequencies",
                width=1000,
                height=800,
                visible=FALSE,
                renderFun=".showBuildModelFrequencies",
                clearWith=list(
                    "buildModel_variables_long_actor",
                    "buildModel_variables_long_time",
                    "buildModel_variables_long_action",
                    "buildModel_variables_long_order",
                    "buildModel_variables_long_group",
                    "buildModel_scaling",
                    "buildModel_threshold")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="centralityTitle",
                title="Centrality",
                visible=FALSE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="centralityContent",
                visible=FALSE,
                clearWith=list(
                    "buildModel_variables_long_actor",
                    "buildModel_variables_long_time",
                    "buildModel_variables_long_action",
                    "buildModel_variables_long_order",
                    "buildModel_variables_long_group",
                    "buildModel_scaling",
                    "buildModel_threshold",
                    "centrality_loops",
                    "centrality_normalize",
                    "centrality_Betweenness",
                    "centrality_BetweennessRSP",
                    "centrality_Closeness",
                    "centrality_ClosenessIn",
                    "centrality_ClosenessOut",
                    "centrality_Clustering",
                    "centrality_Diffusion",
                    "centrality_InStrength",
                    "centrality_OutStrength")))
            self$add(jmvcore::Table$new(
                options=options,
                name="centralityTable",
                title="Centrality Measures",
                visible=FALSE,
                columns=list(
                    list(
                        `name`="state", 
                        `type`="text")),
                clearWith=list(
                    "buildModel_variables_long_actor",
                    "buildModel_variables_long_time",
                    "buildModel_variables_long_action",
                    "buildModel_variables_long_order",
                    "buildModel_variables_long_group",
                    "buildModel_scaling",
                    "buildModel_threshold",
                    "centrality_loops",
                    "centrality_normalize",
                    "centrality_Betweenness",
                    "centrality_BetweennessRSP",
                    "centrality_Closeness",
                    "centrality_ClosenessIn",
                    "centrality_ClosenessOut",
                    "centrality_Clustering",
                    "centrality_Diffusion",
                    "centrality_InStrength",
                    "centrality_OutStrength")))
            self$add(jmvcore::Image$new(
                options=options,
                name="centrality_plot",
                width=1000,
                height=800,
                visible=FALSE,
                renderFun=".showCentralityPlot",
                clearWith=list(
                    "buildModel_variables_long_actor",
                    "buildModel_variables_long_time",
                    "buildModel_variables_long_action",
                    "buildModel_variables_long_order",
                    "buildModel_variables_long_group",
                    "buildModel_scaling",
                    "buildModel_threshold",
                    "centrality_loops",
                    "centrality_normalize",
                    "centrality_Betweenness",
                    "centrality_BetweennessRSP",
                    "centrality_Closeness",
                    "centrality_ClosenessIn",
                    "centrality_ClosenessOut",
                    "centrality_Clustering",
                    "centrality_Diffusion",
                    "centrality_InStrength",
                    "centrality_OutStrength")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="communityTitle",
                title="Community",
                visible=FALSE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="communityErrorText",
                title="Error",
                visible=FALSE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="communityContent",
                visible=FALSE,
                clearWith=list(
                    "buildModel_variables_long_actor",
                    "buildModel_variables_long_time",
                    "buildModel_variables_long_action",
                    "buildModel_variables_long_order",
                    "buildModel_variables_long_group",
                    "buildModel_scaling",
                    "buildModel_threshold",
                    "community_methods",
                    "community_gamma")))
            self$add(jmvcore::Image$new(
                options=options,
                name="community_plot",
                width=1000,
                height=800,
                visible=FALSE,
                renderFun=".showCommunityPlot",
                clearWith=list(
                    "buildModel_variables_long_actor",
                    "buildModel_variables_long_time",
                    "buildModel_variables_long_action",
                    "buildModel_variables_long_order",
                    "buildModel_variables_long_group",
                    "buildModel_scaling",
                    "buildModel_threshold",
                    "community_methods",
                    "community_gamma")))
            self$add(jmvcore::Table$new(
                options=options,
                name="communityTable",
                title="Community Assignments",
                visible=FALSE,
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text"),
                    list(
                        `name`="state", 
                        `title`="State", 
                        `type`="text")),
                clearWith=list(
                    "buildModel_variables_long_actor",
                    "buildModel_variables_long_time",
                    "buildModel_variables_long_action",
                    "buildModel_variables_long_order",
                    "buildModel_variables_long_group",
                    "buildModel_scaling",
                    "buildModel_threshold",
                    "community_methods",
                    "community_gamma")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="cliquesTitle",
                title="Cliques",
                visible=FALSE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="cliquesContent",
                visible=FALSE,
                clearWith=list(
                    "buildModel_variables_long_actor",
                    "buildModel_variables_long_time",
                    "buildModel_variables_long_action",
                    "buildModel_variables_long_order",
                    "buildModel_variables_long_group",
                    "buildModel_scaling",
                    "buildModel_threshold",
                    "cliques_size",
                    "cliques_threshold")))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    cliques_plot1 = function() private$.items[["cliques_plot1"]],
                    cliques_plot2 = function() private$.items[["cliques_plot2"]],
                    cliques_plot3 = function() private$.items[["cliques_plot3"]],
                    cliques_plot4 = function() private$.items[["cliques_plot4"]],
                    cliques_plot5 = function() private$.items[["cliques_plot5"]],
                    cliques_plot6 = function() private$.items[["cliques_plot6"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="cliques_multiple_plot",
                            title="",
                            clearWith=list(
                    "buildModel_variables_long_actor",
                    "buildModel_variables_long_time",
                    "buildModel_variables_long_action",
                    "buildModel_variables_long_order",
                    "buildModel_variables_long_group",
                    "buildModel_scaling",
                    "buildModel_threshold",
                    "cliques_size",
                    "cliques_threshold",
                    "cliques_plot_cut",
                    "cliques_plot_min_value",
                    "cliques_plot_edge_label_size",
                    "cliques_plot_node_size",
                    "cliques_plot_node_label_size",
                    "cliques_plot_layout"))
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="cliques_plot1",
                            width=1000,
                            height=800,
                            visible=TRUE,
                            renderFun=".showCliquesPlot1"))
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="cliques_plot2",
                            width=1000,
                            height=800,
                            visible=TRUE,
                            renderFun=".showCliquesPlot2"))
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="cliques_plot3",
                            width=1000,
                            height=800,
                            visible=TRUE,
                            renderFun=".showCliquesPlot3"))
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="cliques_plot4",
                            width=1000,
                            height=800,
                            visible=TRUE,
                            renderFun=".showCliquesPlot4"))
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="cliques_plot5",
                            width=1000,
                            height=800,
                            visible=TRUE,
                            renderFun=".showCliquesPlot5"))
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="cliques_plot6",
                            width=1000,
                            height=800,
                            visible=TRUE,
                            renderFun=".showCliquesPlot6"))}))$new(options=options))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="bootstrapTitle",
                title="Bootstrap",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="bootstrapTable",
                title="Bootstrap Results",
                visible=FALSE,
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text"),
                    list(
                        `name`="from", 
                        `title`="From", 
                        `type`="text"),
                    list(
                        `name`="to", 
                        `title`="To", 
                        `type`="text"),
                    list(
                        `name`="weight", 
                        `title`="Weight", 
                        `type`="number"),
                    list(
                        `name`="p_value", 
                        `title`="p-value", 
                        `type`="number"),
                    list(
                        `name`="cr_lower", 
                        `title`="CR Lower", 
                        `type`="number"),
                    list(
                        `name`="cr_upper", 
                        `title`="CR Upper", 
                        `type`="number"),
                    list(
                        `name`="ci_lower", 
                        `title`="CI Lower", 
                        `type`="number"),
                    list(
                        `name`="ci_upper", 
                        `title`="CI Upper", 
                        `type`="number"),
                    list(
                        `name`="significant", 
                        `title`="Significant", 
                        `type`="text")),
                clearWith=list(
                    "buildModel_variables_long_actor",
                    "buildModel_variables_long_time",
                    "buildModel_variables_long_action",
                    "buildModel_variables_long_order",
                    "buildModel_variables_long_group",
                    "buildModel_scaling",
                    "buildModel_threshold",
                    "bootstrap_iteration",
                    "bootstrap_level",
                    "bootstrap_method",
                    "bootstrap_range_low",
                    "bootstrap_range_up",
                    "bootstrap_threshold")))
            self$add(jmvcore::Image$new(
                options=options,
                name="bootstrap_plot",
                width=1000,
                height=800,
                visible=FALSE,
                renderFun=".showBootstrapPlot",
                clearWith=list(
                    "buildModel_variables_long_actor",
                    "buildModel_variables_long_time",
                    "buildModel_variables_long_action",
                    "buildModel_variables_long_order",
                    "buildModel_variables_long_group",
                    "buildModel_scaling",
                    "buildModel_threshold",
                    "bootstrap_iteration",
                    "bootstrap_level",
                    "bootstrap_method",
                    "bootstrap_range_low",
                    "bootstrap_range_up",
                    "bootstrap_threshold",
                    "bootstrap_plot_cut",
                    "bootstrap_plot_min_value",
                    "bootstrap_plot_edge_label_size",
                    "bootstrap_plot_node_size",
                    "bootstrap_plot_node_label_size",
                    "bootstrap_plot_layout")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="permutationTitle",
                title="Permutation",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="permutationContent",
                title="Permutation Test Results",
                visible=FALSE,
                columns=list(
                    list(
                        `name`="group_comparison", 
                        `title`="Group Comparison", 
                        `type`="text"),
                    list(
                        `name`="edge_name", 
                        `type`="text"),
                    list(
                        `name`="diff_true", 
                        `type`="number"),
                    list(
                        `name`="effect_size", 
                        `type`="number"),
                    list(
                        `name`="p_value", 
                        `type`="number")),
                clearWith=list(
                    "buildModel_variables_long_actor",
                    "buildModel_variables_long_time",
                    "buildModel_variables_long_action",
                    "buildModel_variables_long_order",
                    "buildModel_variables_long_group",
                    "buildModel_scaling",
                    "buildModel_threshold",
                    "permutation_iter",
                    "permutation_paired",
                    "permutation_level")))
            self$add(jmvcore::Image$new(
                options=options,
                name="permutation_plot",
                width=1000,
                height=1000,
                visible=FALSE,
                renderFun=".showPermutationPlot",
                clearWith=list(
                    "buildModel_variables_long_actor",
                    "buildModel_variables_long_time",
                    "buildModel_variables_long_action",
                    "buildModel_variables_long_order",
                    "buildModel_variables_long_group",
                    "buildModel_scaling",
                    "buildModel_threshold",
                    "permutation_iter",
                    "permutation_paired",
                    "permutation_level")))
            self$add(jmvcore::Image$new(
                options=options,
                name="compare_network_diff_plot",
                title="Network Difference Plot",
                width=1000,
                height=800,
                visible=FALSE,
                renderFun=".showCompareNetworkDiffPlot",
                clearWith=list(
                    "buildModel_variables_long_actor",
                    "buildModel_variables_long_time",
                    "buildModel_variables_long_action",
                    "buildModel_variables_long_order",
                    "buildModel_variables_long_group",
                    "buildModel_scaling",
                    "compare_network_diff_plot_cut",
                    "compare_network_diff_plot_min_value",
                    "compare_network_diff_plot_edge_label_size",
                    "compare_network_diff_plot_node_size",
                    "compare_network_diff_plot_node_label_size",
                    "compare_network_diff_plot_layout")))
            self$add(jmvcore::Html$new(
                options=options,
                name="compareInstructions",
                visible=FALSE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="compareTitle",
                title="Compare Network Properties",
                visible=FALSE))
            self$add(jmvcore::Image$new(
                options=options,
                name="compare_plot",
                title="Group Comparison Plot",
                width=700,
                height=500,
                visible=FALSE,
                renderFun=".showComparePlot",
                clearWith=list(
                    "buildModel_variables_long_actor",
                    "buildModel_variables_long_time",
                    "buildModel_variables_long_action",
                    "buildModel_variables_long_order",
                    "buildModel_variables_long_group",
                    "buildModel_scaling",
                    "buildModel_threshold",
                    "compare_group_i",
                    "compare_group_j",
                    "compare_scaling",
                    "compare_plot_type")))
            self$add(jmvcore::Table$new(
                options=options,
                name="compareSummaryTable",
                title="Summary Metrics",
                visible=FALSE,
                columns=list(
                    list(
                        `name`="metric", 
                        `title`="Metric", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="number")),
                clearWith=list(
                    "buildModel_variables_long_actor",
                    "buildModel_variables_long_time",
                    "buildModel_variables_long_action",
                    "buildModel_variables_long_order",
                    "buildModel_variables_long_group",
                    "buildModel_scaling",
                    "buildModel_threshold",
                    "compare_group_i",
                    "compare_group_j",
                    "compare_scaling")))
            self$add(jmvcore::Table$new(
                options=options,
                name="compareNetworkTable",
                title="Network Properties",
                visible=FALSE,
                columns=list(
                    list(
                        `name`="metric", 
                        `title`="Metric", 
                        `type`="text"),
                    list(
                        `name`="group_i", 
                        `title`="Group 1", 
                        `type`="number"),
                    list(
                        `name`="group_j", 
                        `title`="Group 2", 
                        `type`="number")),
                clearWith=list(
                    "buildModel_variables_long_actor",
                    "buildModel_variables_long_time",
                    "buildModel_variables_long_action",
                    "buildModel_variables_long_order",
                    "buildModel_variables_long_group",
                    "buildModel_scaling",
                    "buildModel_threshold",
                    "compare_group_i",
                    "compare_group_j",
                    "compare_scaling")))}))

GroupCoOccurrenceTNABase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "GroupCoOccurrenceTNABase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "JTNA",
                name = "GroupCoOccurrenceTNA",
                version = c(1,12,0),
                options = options,
                results = GroupCoOccurrenceTNAResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Group Co-occurrence Network Analysis
#'
#' 
#' @param data .
#' @param buildModel_variables_long_action The column containing the
#'   actions/states/events to analyze. Each unique value becomes a node in the
#'   co-occurrence network.
#' @param buildModel_variables_long_actor The column identifying
#'   individuals/actors. Used to separate sequences by person.
#' @param buildModel_variables_long_time Timestamp column for ordering events
#'   chronologically. Use this OR Order, not both.
#' @param buildModel_variables_long_order Numeric column indicating the
#'   sequence position of each event. Use this OR Time, not both.
#' @param buildModel_variables_long_group The column defining groups for
#'   comparison (e.g., treatment vs control). A separate co-occurrence network
#'   will be built for each group.
#' @param buildModel_scaling .
#' @param buildModel_show_matrix .
#' @param buildModel_threshold .
#' @param buildModel_show_plot .
#' @param buildModel_plot_cut .
#' @param buildModel_plot_min_value .
#' @param buildModel_plot_edge_label_size .
#' @param buildModel_plot_node_size .
#' @param buildModel_plot_node_label_size .
#' @param buildModel_plot_layout .
#' @param buildModel_show_histo .
#' @param buildModel_show_frequencies .
#' @param centrality_loops .
#' @param centrality_normalize .
#' @param centrality_show_table .
#' @param centrality_show_plot .
#' @param centrality_Betweenness .
#' @param centrality_BetweennessRSP .
#' @param centrality_Closeness .
#' @param centrality_ClosenessIn .
#' @param centrality_ClosenessOut .
#' @param centrality_Clustering .
#' @param centrality_Diffusion .
#' @param centrality_InStrength .
#' @param centrality_OutStrength .
#' @param community_methods .
#' @param community_gamma .
#' @param community_show_plot .
#' @param community_show_table .
#' @param cliques_size .
#' @param cliques_threshold .
#' @param cliques_show_text .
#' @param cliques_show_plot .
#' @param cliques_plot_cut .
#' @param cliques_plot_min_value .
#' @param cliques_plot_edge_label_size .
#' @param cliques_plot_node_size .
#' @param cliques_plot_node_label_size .
#' @param cliques_plot_layout .
#' @param bootstrap_iteration .
#' @param bootstrap_level .
#' @param bootstrap_method .
#' @param bootstrap_range_low .
#' @param bootstrap_range_up .
#' @param bootstrap_threshold .
#' @param bootstrap_show_table .
#' @param bootstrap_table_max_rows .
#' @param bootstrap_table_show_all .
#' @param bootstrap_table_significant_only .
#' @param bootstrap_show_plot .
#' @param bootstrap_plot_cut .
#' @param bootstrap_plot_min_value .
#' @param bootstrap_plot_edge_label_size .
#' @param bootstrap_plot_node_size .
#' @param bootstrap_plot_node_label_size .
#' @param bootstrap_plot_layout .
#' @param permutation_show_text .
#' @param permutation_show_plot .
#' @param permutation_iter .
#' @param permutation_paired .
#' @param permutation_level .
#' @param permutation_table_max_rows .
#' @param permutation_table_show_all .
#' @param compare_show_summary .
#' @param compare_show_network .
#' @param compare_show_plot .
#' @param compare_group_i .
#' @param compare_group_j .
#' @param compare_scaling .
#' @param compare_plot_type .
#' @param compare_show_network_diff_plot .
#' @param compare_network_diff_plot_cut .
#' @param compare_network_diff_plot_min_value .
#' @param compare_network_diff_plot_edge_label_size .
#' @param compare_network_diff_plot_node_size .
#' @param compare_network_diff_plot_node_label_size .
#' @param compare_network_diff_plot_layout .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$errorText} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$tnaTitle} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$buildModelTitle} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$buildModelContent} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$buildModel_plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$buildModel_histo} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$buildModel_frequencies} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$centralityTitle} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$centralityContent} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$centralityTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$centrality_plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$communityTitle} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$communityErrorText} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$communityContent} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$community_plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$communityTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$cliquesTitle} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$cliquesContent} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$cliques_multiple_plot$cliques_plot1} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$cliques_multiple_plot$cliques_plot2} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$cliques_multiple_plot$cliques_plot3} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$cliques_multiple_plot$cliques_plot4} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$cliques_multiple_plot$cliques_plot5} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$cliques_multiple_plot$cliques_plot6} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$bootstrapTitle} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$bootstrapTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$bootstrap_plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$permutationTitle} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$permutationContent} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$permutation_plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$compare_network_diff_plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$compareInstructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$compareTitle} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$compare_plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$compareSummaryTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$compareNetworkTable} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$centralityTable$asDF}
#'
#' \code{as.data.frame(results$centralityTable)}
#'
#' @export
GroupCoOccurrenceTNA <- function(
    data,
    buildModel_variables_long_action,
    buildModel_variables_long_actor,
    buildModel_variables_long_time,
    buildModel_variables_long_order,
    buildModel_variables_long_group,
    buildModel_scaling = "noScaling",
    buildModel_show_matrix = FALSE,
    buildModel_threshold = 900,
    buildModel_show_plot = TRUE,
    buildModel_plot_cut = 0.1,
    buildModel_plot_min_value = 0.05,
    buildModel_plot_edge_label_size = 1,
    buildModel_plot_node_size = 1,
    buildModel_plot_node_label_size = 1,
    buildModel_plot_layout,
    buildModel_show_histo = FALSE,
    buildModel_show_frequencies = FALSE,
    centrality_loops = FALSE,
    centrality_normalize = FALSE,
    centrality_show_table = FALSE,
    centrality_show_plot = FALSE,
    centrality_Betweenness = TRUE,
    centrality_BetweennessRSP = FALSE,
    centrality_Closeness = FALSE,
    centrality_ClosenessIn = FALSE,
    centrality_ClosenessOut = FALSE,
    centrality_Clustering = FALSE,
    centrality_Diffusion = FALSE,
    centrality_InStrength = TRUE,
    centrality_OutStrength = TRUE,
    community_methods = "spinglass",
    community_gamma = 1,
    community_show_plot = FALSE,
    community_show_table = FALSE,
    cliques_size = 2,
    cliques_threshold = 0,
    cliques_show_text = FALSE,
    cliques_show_plot = FALSE,
    cliques_plot_cut = 0.1,
    cliques_plot_min_value = 0,
    cliques_plot_edge_label_size = 1,
    cliques_plot_node_size = 1,
    cliques_plot_node_label_size = 1,
    cliques_plot_layout = "circle",
    bootstrap_iteration = 1000,
    bootstrap_level = 0.05,
    bootstrap_method = "stability",
    bootstrap_range_low = 0.75,
    bootstrap_range_up = 1.25,
    bootstrap_threshold = 0.1,
    bootstrap_show_table = FALSE,
    bootstrap_table_max_rows = 20,
    bootstrap_table_show_all = FALSE,
    bootstrap_table_significant_only = FALSE,
    bootstrap_show_plot = FALSE,
    bootstrap_plot_cut = 0.1,
    bootstrap_plot_min_value = 0.05,
    bootstrap_plot_edge_label_size = 1,
    bootstrap_plot_node_size = 1,
    bootstrap_plot_node_label_size = 1,
    bootstrap_plot_layout,
    permutation_show_text = FALSE,
    permutation_show_plot = FALSE,
    permutation_iter = 1000,
    permutation_paired = FALSE,
    permutation_level = 0.05,
    permutation_table_max_rows = 20,
    permutation_table_show_all = FALSE,
    compare_show_summary = FALSE,
    compare_show_network = FALSE,
    compare_show_plot = FALSE,
    compare_group_i,
    compare_group_j,
    compare_scaling = "none",
    compare_plot_type = "heatmap",
    compare_show_network_diff_plot = FALSE,
    compare_network_diff_plot_cut = 0.1,
    compare_network_diff_plot_min_value = 0.05,
    compare_network_diff_plot_edge_label_size = 1,
    compare_network_diff_plot_node_size = 1,
    compare_network_diff_plot_node_label_size = 1,
    compare_network_diff_plot_layout = "circle") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("GroupCoOccurrenceTNA requires jmvcore to be installed (restart may be required)")

    if ( ! missing(buildModel_variables_long_action)) buildModel_variables_long_action <- jmvcore::resolveQuo(jmvcore::enquo(buildModel_variables_long_action))
    if ( ! missing(buildModel_variables_long_actor)) buildModel_variables_long_actor <- jmvcore::resolveQuo(jmvcore::enquo(buildModel_variables_long_actor))
    if ( ! missing(buildModel_variables_long_time)) buildModel_variables_long_time <- jmvcore::resolveQuo(jmvcore::enquo(buildModel_variables_long_time))
    if ( ! missing(buildModel_variables_long_order)) buildModel_variables_long_order <- jmvcore::resolveQuo(jmvcore::enquo(buildModel_variables_long_order))
    if ( ! missing(buildModel_variables_long_group)) buildModel_variables_long_group <- jmvcore::resolveQuo(jmvcore::enquo(buildModel_variables_long_group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(buildModel_variables_long_action), buildModel_variables_long_action, NULL),
            `if`( ! missing(buildModel_variables_long_actor), buildModel_variables_long_actor, NULL),
            `if`( ! missing(buildModel_variables_long_time), buildModel_variables_long_time, NULL),
            `if`( ! missing(buildModel_variables_long_order), buildModel_variables_long_order, NULL),
            `if`( ! missing(buildModel_variables_long_group), buildModel_variables_long_group, NULL))


    options <- GroupCoOccurrenceTNAOptions$new(
        buildModel_variables_long_action = buildModel_variables_long_action,
        buildModel_variables_long_actor = buildModel_variables_long_actor,
        buildModel_variables_long_time = buildModel_variables_long_time,
        buildModel_variables_long_order = buildModel_variables_long_order,
        buildModel_variables_long_group = buildModel_variables_long_group,
        buildModel_scaling = buildModel_scaling,
        buildModel_show_matrix = buildModel_show_matrix,
        buildModel_threshold = buildModel_threshold,
        buildModel_show_plot = buildModel_show_plot,
        buildModel_plot_cut = buildModel_plot_cut,
        buildModel_plot_min_value = buildModel_plot_min_value,
        buildModel_plot_edge_label_size = buildModel_plot_edge_label_size,
        buildModel_plot_node_size = buildModel_plot_node_size,
        buildModel_plot_node_label_size = buildModel_plot_node_label_size,
        buildModel_plot_layout = buildModel_plot_layout,
        buildModel_show_histo = buildModel_show_histo,
        buildModel_show_frequencies = buildModel_show_frequencies,
        centrality_loops = centrality_loops,
        centrality_normalize = centrality_normalize,
        centrality_show_table = centrality_show_table,
        centrality_show_plot = centrality_show_plot,
        centrality_Betweenness = centrality_Betweenness,
        centrality_BetweennessRSP = centrality_BetweennessRSP,
        centrality_Closeness = centrality_Closeness,
        centrality_ClosenessIn = centrality_ClosenessIn,
        centrality_ClosenessOut = centrality_ClosenessOut,
        centrality_Clustering = centrality_Clustering,
        centrality_Diffusion = centrality_Diffusion,
        centrality_InStrength = centrality_InStrength,
        centrality_OutStrength = centrality_OutStrength,
        community_methods = community_methods,
        community_gamma = community_gamma,
        community_show_plot = community_show_plot,
        community_show_table = community_show_table,
        cliques_size = cliques_size,
        cliques_threshold = cliques_threshold,
        cliques_show_text = cliques_show_text,
        cliques_show_plot = cliques_show_plot,
        cliques_plot_cut = cliques_plot_cut,
        cliques_plot_min_value = cliques_plot_min_value,
        cliques_plot_edge_label_size = cliques_plot_edge_label_size,
        cliques_plot_node_size = cliques_plot_node_size,
        cliques_plot_node_label_size = cliques_plot_node_label_size,
        cliques_plot_layout = cliques_plot_layout,
        bootstrap_iteration = bootstrap_iteration,
        bootstrap_level = bootstrap_level,
        bootstrap_method = bootstrap_method,
        bootstrap_range_low = bootstrap_range_low,
        bootstrap_range_up = bootstrap_range_up,
        bootstrap_threshold = bootstrap_threshold,
        bootstrap_show_table = bootstrap_show_table,
        bootstrap_table_max_rows = bootstrap_table_max_rows,
        bootstrap_table_show_all = bootstrap_table_show_all,
        bootstrap_table_significant_only = bootstrap_table_significant_only,
        bootstrap_show_plot = bootstrap_show_plot,
        bootstrap_plot_cut = bootstrap_plot_cut,
        bootstrap_plot_min_value = bootstrap_plot_min_value,
        bootstrap_plot_edge_label_size = bootstrap_plot_edge_label_size,
        bootstrap_plot_node_size = bootstrap_plot_node_size,
        bootstrap_plot_node_label_size = bootstrap_plot_node_label_size,
        bootstrap_plot_layout = bootstrap_plot_layout,
        permutation_show_text = permutation_show_text,
        permutation_show_plot = permutation_show_plot,
        permutation_iter = permutation_iter,
        permutation_paired = permutation_paired,
        permutation_level = permutation_level,
        permutation_table_max_rows = permutation_table_max_rows,
        permutation_table_show_all = permutation_table_show_all,
        compare_show_summary = compare_show_summary,
        compare_show_network = compare_show_network,
        compare_show_plot = compare_show_plot,
        compare_group_i = compare_group_i,
        compare_group_j = compare_group_j,
        compare_scaling = compare_scaling,
        compare_plot_type = compare_plot_type,
        compare_show_network_diff_plot = compare_show_network_diff_plot,
        compare_network_diff_plot_cut = compare_network_diff_plot_cut,
        compare_network_diff_plot_min_value = compare_network_diff_plot_min_value,
        compare_network_diff_plot_edge_label_size = compare_network_diff_plot_edge_label_size,
        compare_network_diff_plot_node_size = compare_network_diff_plot_node_size,
        compare_network_diff_plot_node_label_size = compare_network_diff_plot_node_label_size,
        compare_network_diff_plot_layout = compare_network_diff_plot_layout)

    analysis <- GroupCoOccurrenceTNAClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

