
# This file is automatically generated, you probably don't want to edit this

SNAOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SNAOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            sna_from = NULL,
            sna_to = NULL,
            sna_weight = NULL,
            sna_aggregate = "sum",
            sna_show_matrix = FALSE,
            sna_show_plot = TRUE,
            sna_plot_cut = 0.1,
            sna_plot_min_value = 0.05,
            sna_plot_edge_label_size = 1,
            sna_plot_node_size = 1,
            sna_plot_node_label_size = 1,
            sna_plot_layout = NULL,
            centrality_show_table = FALSE,
            centrality_show_plot = FALSE,
            centrality_OutStrength = TRUE,
            centrality_InStrength = TRUE,
            centrality_Betweenness = TRUE,
            centrality_loops = FALSE,
            centrality_normalize = FALSE, ...) {

            super$initialize(
                package="JTNA",
                name="SNA",
                requiresData=TRUE,
                ...)

            private$..sna_from <- jmvcore::OptionVariable$new(
                "sna_from",
                sna_from)
            private$..sna_to <- jmvcore::OptionVariable$new(
                "sna_to",
                sna_to)
            private$..sna_weight <- jmvcore::OptionVariable$new(
                "sna_weight",
                sna_weight)
            private$..sna_aggregate <- jmvcore::OptionList$new(
                "sna_aggregate",
                sna_aggregate,
                options=list(
                    "sum",
                    "mean",
                    "max",
                    "min"),
                default="sum")
            private$..sna_show_matrix <- jmvcore::OptionBool$new(
                "sna_show_matrix",
                sna_show_matrix,
                default=FALSE)
            private$..sna_show_plot <- jmvcore::OptionBool$new(
                "sna_show_plot",
                sna_show_plot,
                default=TRUE)
            private$..sna_plot_cut <- jmvcore::OptionNumber$new(
                "sna_plot_cut",
                sna_plot_cut,
                default=0.1,
                min=0,
                max=1)
            private$..sna_plot_min_value <- jmvcore::OptionNumber$new(
                "sna_plot_min_value",
                sna_plot_min_value,
                default=0.05,
                min=0,
                max=1)
            private$..sna_plot_edge_label_size <- jmvcore::OptionNumber$new(
                "sna_plot_edge_label_size",
                sna_plot_edge_label_size,
                default=1,
                min=0,
                max=10)
            private$..sna_plot_node_size <- jmvcore::OptionNumber$new(
                "sna_plot_node_size",
                sna_plot_node_size,
                default=1,
                min=0,
                max=2)
            private$..sna_plot_node_label_size <- jmvcore::OptionNumber$new(
                "sna_plot_node_label_size",
                sna_plot_node_label_size,
                default=1,
                min=0,
                max=10)
            private$..sna_plot_layout <- jmvcore::OptionList$new(
                "sna_plot_layout",
                sna_plot_layout,
                options=list(
                    "circle",
                    "spring",
                    "layout_with_kk",
                    "layout_with_graphopt",
                    "layout_with_gem",
                    "layout_with_drl",
                    "layout_as_star",
                    "layout_on_grid",
                    "layout_nicely",
                    "layout_with_fr",
                    "layout_with_dh",
                    "layout_with_lgl",
                    "layout_with_sugiyama",
                    "layout_randomly"))
            private$..centrality_show_table <- jmvcore::OptionBool$new(
                "centrality_show_table",
                centrality_show_table,
                default=FALSE)
            private$..centrality_show_plot <- jmvcore::OptionBool$new(
                "centrality_show_plot",
                centrality_show_plot,
                default=FALSE)
            private$..centrality_OutStrength <- jmvcore::OptionBool$new(
                "centrality_OutStrength",
                centrality_OutStrength,
                default=TRUE)
            private$..centrality_InStrength <- jmvcore::OptionBool$new(
                "centrality_InStrength",
                centrality_InStrength,
                default=TRUE)
            private$..centrality_Betweenness <- jmvcore::OptionBool$new(
                "centrality_Betweenness",
                centrality_Betweenness,
                default=TRUE)
            private$..centrality_loops <- jmvcore::OptionBool$new(
                "centrality_loops",
                centrality_loops,
                default=FALSE)
            private$..centrality_normalize <- jmvcore::OptionBool$new(
                "centrality_normalize",
                centrality_normalize,
                default=FALSE)

            self$.addOption(private$..sna_from)
            self$.addOption(private$..sna_to)
            self$.addOption(private$..sna_weight)
            self$.addOption(private$..sna_aggregate)
            self$.addOption(private$..sna_show_matrix)
            self$.addOption(private$..sna_show_plot)
            self$.addOption(private$..sna_plot_cut)
            self$.addOption(private$..sna_plot_min_value)
            self$.addOption(private$..sna_plot_edge_label_size)
            self$.addOption(private$..sna_plot_node_size)
            self$.addOption(private$..sna_plot_node_label_size)
            self$.addOption(private$..sna_plot_layout)
            self$.addOption(private$..centrality_show_table)
            self$.addOption(private$..centrality_show_plot)
            self$.addOption(private$..centrality_OutStrength)
            self$.addOption(private$..centrality_InStrength)
            self$.addOption(private$..centrality_Betweenness)
            self$.addOption(private$..centrality_loops)
            self$.addOption(private$..centrality_normalize)
        }),
    active = list(
        sna_from = function() private$..sna_from$value,
        sna_to = function() private$..sna_to$value,
        sna_weight = function() private$..sna_weight$value,
        sna_aggregate = function() private$..sna_aggregate$value,
        sna_show_matrix = function() private$..sna_show_matrix$value,
        sna_show_plot = function() private$..sna_show_plot$value,
        sna_plot_cut = function() private$..sna_plot_cut$value,
        sna_plot_min_value = function() private$..sna_plot_min_value$value,
        sna_plot_edge_label_size = function() private$..sna_plot_edge_label_size$value,
        sna_plot_node_size = function() private$..sna_plot_node_size$value,
        sna_plot_node_label_size = function() private$..sna_plot_node_label_size$value,
        sna_plot_layout = function() private$..sna_plot_layout$value,
        centrality_show_table = function() private$..centrality_show_table$value,
        centrality_show_plot = function() private$..centrality_show_plot$value,
        centrality_OutStrength = function() private$..centrality_OutStrength$value,
        centrality_InStrength = function() private$..centrality_InStrength$value,
        centrality_Betweenness = function() private$..centrality_Betweenness$value,
        centrality_loops = function() private$..centrality_loops$value,
        centrality_normalize = function() private$..centrality_normalize$value),
    private = list(
        ..sna_from = NA,
        ..sna_to = NA,
        ..sna_weight = NA,
        ..sna_aggregate = NA,
        ..sna_show_matrix = NA,
        ..sna_show_plot = NA,
        ..sna_plot_cut = NA,
        ..sna_plot_min_value = NA,
        ..sna_plot_edge_label_size = NA,
        ..sna_plot_node_size = NA,
        ..sna_plot_node_label_size = NA,
        ..sna_plot_layout = NA,
        ..centrality_show_table = NA,
        ..centrality_show_plot = NA,
        ..centrality_OutStrength = NA,
        ..centrality_InStrength = NA,
        ..centrality_Betweenness = NA,
        ..centrality_loops = NA,
        ..centrality_normalize = NA)
)

SNAResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SNAResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        errorText = function() private$.items[["errorText"]],
        snaTitle = function() private$.items[["snaTitle"]],
        snaModelTitle = function() private$.items[["snaModelTitle"]],
        snaModelContent = function() private$.items[["snaModelContent"]],
        sna_plot = function() private$.items[["sna_plot"]],
        centralityTitle = function() private$.items[["centralityTitle"]],
        centralityTable = function() private$.items[["centralityTable"]],
        centrality_plot = function() private$.items[["centrality_plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Social Network Analysis",
                refs=list(
                    "JTNA",
                    "SNA"))
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="errorText",
                title="Error",
                visible=FALSE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="snaTitle",
                title="SNA",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="snaModelTitle",
                title="Model",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="snaModelContent",
                visible=FALSE,
                clearWith=list(
                    "sna_from",
                    "sna_to",
                    "sna_weight",
                    "sna_aggregate")))
            self$add(jmvcore::Image$new(
                options=options,
                name="sna_plot",
                width=600,
                height=600,
                visible=FALSE,
                renderFun=".showSNAPlot",
                clearWith=list(
                    "sna_from",
                    "sna_to",
                    "sna_weight",
                    "sna_aggregate",
                    "sna_plot_cut",
                    "sna_plot_min_value",
                    "sna_plot_edge_label_size",
                    "sna_plot_node_size",
                    "sna_plot_node_label_size",
                    "sna_plot_layout")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="centralityTitle",
                title="Centrality",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="centralityTable",
                title="Centrality Measures",
                visible=FALSE,
                columns=list(
                    list(
                        `name`="state", 
                        `type`="text")),
                clearWith=list(
                    "sna_from",
                    "sna_to",
                    "sna_weight",
                    "sna_aggregate",
                    "centrality_loops",
                    "centrality_normalize",
                    "centrality_OutStrength",
                    "centrality_InStrength",
                    "centrality_Betweenness")))
            self$add(jmvcore::Image$new(
                options=options,
                name="centrality_plot",
                width=600,
                height=600,
                visible=FALSE,
                renderFun=".showCentralityPlot",
                clearWith=list(
                    "sna_from",
                    "sna_to",
                    "sna_weight",
                    "sna_aggregate",
                    "centrality_loops",
                    "centrality_normalize",
                    "centrality_OutStrength",
                    "centrality_InStrength",
                    "centrality_Betweenness")))}))

SNABase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SNABase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "JTNA",
                name = "SNA",
                version = c(1,10,0),
                options = options,
                results = SNAResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Social Network Analysis
#'
#' 
#' @param data .
#' @param sna_from The column containing the source node of each edge
#'   (required).
#' @param sna_to The column containing the target node of each edge
#'   (required).
#' @param sna_weight The column containing edge weights. If not provided,
#'   defaults to 1 for unweighted networks.
#' @param sna_aggregate .
#' @param sna_show_matrix .
#' @param sna_show_plot .
#' @param sna_plot_cut .
#' @param sna_plot_min_value .
#' @param sna_plot_edge_label_size .
#' @param sna_plot_node_size .
#' @param sna_plot_node_label_size .
#' @param sna_plot_layout .
#' @param centrality_show_table .
#' @param centrality_show_plot .
#' @param centrality_OutStrength .
#' @param centrality_InStrength .
#' @param centrality_Betweenness .
#' @param centrality_loops .
#' @param centrality_normalize .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$errorText} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$snaTitle} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$snaModelTitle} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$snaModelContent} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$sna_plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$centralityTitle} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$centralityTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$centrality_plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$centralityTable$asDF}
#'
#' \code{as.data.frame(results$centralityTable)}
#'
#' @export
SNA <- function(
    data,
    sna_from,
    sna_to,
    sna_weight,
    sna_aggregate = "sum",
    sna_show_matrix = FALSE,
    sna_show_plot = TRUE,
    sna_plot_cut = 0.1,
    sna_plot_min_value = 0.05,
    sna_plot_edge_label_size = 1,
    sna_plot_node_size = 1,
    sna_plot_node_label_size = 1,
    sna_plot_layout,
    centrality_show_table = FALSE,
    centrality_show_plot = FALSE,
    centrality_OutStrength = TRUE,
    centrality_InStrength = TRUE,
    centrality_Betweenness = TRUE,
    centrality_loops = FALSE,
    centrality_normalize = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("SNA requires jmvcore to be installed (restart may be required)")

    if ( ! missing(sna_from)) sna_from <- jmvcore::resolveQuo(jmvcore::enquo(sna_from))
    if ( ! missing(sna_to)) sna_to <- jmvcore::resolveQuo(jmvcore::enquo(sna_to))
    if ( ! missing(sna_weight)) sna_weight <- jmvcore::resolveQuo(jmvcore::enquo(sna_weight))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(sna_from), sna_from, NULL),
            `if`( ! missing(sna_to), sna_to, NULL),
            `if`( ! missing(sna_weight), sna_weight, NULL))


    options <- SNAOptions$new(
        sna_from = sna_from,
        sna_to = sna_to,
        sna_weight = sna_weight,
        sna_aggregate = sna_aggregate,
        sna_show_matrix = sna_show_matrix,
        sna_show_plot = sna_show_plot,
        sna_plot_cut = sna_plot_cut,
        sna_plot_min_value = sna_plot_min_value,
        sna_plot_edge_label_size = sna_plot_edge_label_size,
        sna_plot_node_size = sna_plot_node_size,
        sna_plot_node_label_size = sna_plot_node_label_size,
        sna_plot_layout = sna_plot_layout,
        centrality_show_table = centrality_show_table,
        centrality_show_plot = centrality_show_plot,
        centrality_OutStrength = centrality_OutStrength,
        centrality_InStrength = centrality_InStrength,
        centrality_Betweenness = centrality_Betweenness,
        centrality_loops = centrality_loops,
        centrality_normalize = centrality_normalize)

    analysis <- SNAClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

