
# This file is automatically generated, you probably don't want to edit this

SNAOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SNAOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            sna_from = NULL,
            sna_to = NULL,
            sna_weight = NULL,
            sna_group = NULL,
            sna_aggregate = "sum",
            sna_show_summary = TRUE,
            sna_show_degree_plot = FALSE,
            sna_show_plot = TRUE,
            sna_plot_node_size_slider = 8,
            sna_plot_edge_size_slider = 6,
            sna_plot_show_node_labels = FALSE,
            sna_plot_show_edge_labels = FALSE,
            sna_plot_cut = 0.1,
            sna_plot_min_value = 0.05,
            sna_plot_edge_label_size = 1,
            sna_plot_node_size = 1,
            sna_plot_node_label_size = 1,
            sna_plot_layout = NULL,
            sna_plot_repulsion = 1,
            sna_plot_vsize = 8,
            sna_plot_borders = TRUE,
            sna_plot_border_width = 1,
            sna_plot_asize = 2,
            sna_plot_curve = 0,
            sna_plot_curveAll = FALSE,
            sna_plot_theme = "colorblind",
            sna_plot_edge_color = "default",
            sna_plot_details = FALSE,
            sna_plot_width = 600,
            sna_plot_height = 600,
            centrality_show_table = FALSE,
            centrality_OutStrength = TRUE,
            centrality_InStrength = TRUE,
            centrality_Betweenness = TRUE,
            centrality_BetweennessRSP = FALSE,
            centrality_Closeness = FALSE,
            centrality_ClosenessIn = FALSE,
            centrality_ClosenessOut = FALSE,
            centrality_Diffusion = FALSE,
            centrality_Clustering = FALSE,
            centrality_loops = FALSE,
            centrality_normalize = FALSE,
            community_show_table = FALSE,
            community_walktrap = TRUE,
            community_fast_greedy = TRUE,
            community_label_prop = FALSE,
            community_infomap = FALSE,
            community_edge_betweenness = FALSE,
            community_leading_eigen = FALSE,
            community_spinglass = FALSE,
            edge_betweenness_show_table = FALSE,
            edge_betweenness_directed = TRUE, ...) {

            super$initialize(
                package="JTNA",
                name="SNA",
                requiresData=TRUE,
                ...)

            private$..sna_from <- jmvcore::OptionVariable$new(
                "sna_from",
                sna_from)
            private$..sna_to <- jmvcore::OptionVariable$new(
                "sna_to",
                sna_to)
            private$..sna_weight <- jmvcore::OptionVariable$new(
                "sna_weight",
                sna_weight)
            private$..sna_group <- jmvcore::OptionVariable$new(
                "sna_group",
                sna_group)
            private$..sna_aggregate <- jmvcore::OptionList$new(
                "sna_aggregate",
                sna_aggregate,
                options=list(
                    "sum",
                    "mean",
                    "max",
                    "min"),
                default="sum")
            private$..sna_show_summary <- jmvcore::OptionBool$new(
                "sna_show_summary",
                sna_show_summary,
                default=TRUE)
            private$..sna_show_degree_plot <- jmvcore::OptionBool$new(
                "sna_show_degree_plot",
                sna_show_degree_plot,
                default=FALSE)
            private$..sna_show_plot <- jmvcore::OptionBool$new(
                "sna_show_plot",
                sna_show_plot,
                default=TRUE)
            private$..sna_plot_node_size_slider <- jmvcore::OptionNumber$new(
                "sna_plot_node_size_slider",
                sna_plot_node_size_slider,
                default=8,
                min=1,
                max=30)
            private$..sna_plot_edge_size_slider <- jmvcore::OptionNumber$new(
                "sna_plot_edge_size_slider",
                sna_plot_edge_size_slider,
                default=6,
                min=1,
                max=30)
            private$..sna_plot_show_node_labels <- jmvcore::OptionBool$new(
                "sna_plot_show_node_labels",
                sna_plot_show_node_labels,
                default=FALSE)
            private$..sna_plot_show_edge_labels <- jmvcore::OptionBool$new(
                "sna_plot_show_edge_labels",
                sna_plot_show_edge_labels,
                default=FALSE)
            private$..sna_plot_cut <- jmvcore::OptionNumber$new(
                "sna_plot_cut",
                sna_plot_cut,
                default=0.1,
                min=0,
                max=1)
            private$..sna_plot_min_value <- jmvcore::OptionNumber$new(
                "sna_plot_min_value",
                sna_plot_min_value,
                default=0.05,
                min=0,
                max=1)
            private$..sna_plot_edge_label_size <- jmvcore::OptionNumber$new(
                "sna_plot_edge_label_size",
                sna_plot_edge_label_size,
                default=1,
                min=0,
                max=10)
            private$..sna_plot_node_size <- jmvcore::OptionNumber$new(
                "sna_plot_node_size",
                sna_plot_node_size,
                default=1,
                min=0,
                max=2)
            private$..sna_plot_node_label_size <- jmvcore::OptionNumber$new(
                "sna_plot_node_label_size",
                sna_plot_node_label_size,
                default=1,
                min=0,
                max=10)
            private$..sna_plot_layout <- jmvcore::OptionList$new(
                "sna_plot_layout",
                sna_plot_layout,
                options=list(
                    "circle",
                    "spring",
                    "layout_with_kk",
                    "layout_with_graphopt",
                    "layout_with_gem",
                    "layout_with_drl",
                    "layout_as_star",
                    "layout_on_grid",
                    "layout_nicely",
                    "layout_with_fr",
                    "layout_with_dh",
                    "layout_with_lgl",
                    "layout_with_sugiyama",
                    "layout_randomly"))
            private$..sna_plot_repulsion <- jmvcore::OptionNumber$new(
                "sna_plot_repulsion",
                sna_plot_repulsion,
                default=1,
                min=0.1,
                max=10)
            private$..sna_plot_vsize <- jmvcore::OptionNumber$new(
                "sna_plot_vsize",
                sna_plot_vsize,
                default=8,
                min=1,
                max=30)
            private$..sna_plot_borders <- jmvcore::OptionBool$new(
                "sna_plot_borders",
                sna_plot_borders,
                default=TRUE)
            private$..sna_plot_border_width <- jmvcore::OptionNumber$new(
                "sna_plot_border_width",
                sna_plot_border_width,
                default=1,
                min=0,
                max=5)
            private$..sna_plot_asize <- jmvcore::OptionNumber$new(
                "sna_plot_asize",
                sna_plot_asize,
                default=2,
                min=1,
                max=15)
            private$..sna_plot_curve <- jmvcore::OptionNumber$new(
                "sna_plot_curve",
                sna_plot_curve,
                default=0,
                min=0,
                max=5)
            private$..sna_plot_curveAll <- jmvcore::OptionBool$new(
                "sna_plot_curveAll",
                sna_plot_curveAll,
                default=FALSE)
            private$..sna_plot_theme <- jmvcore::OptionList$new(
                "sna_plot_theme",
                sna_plot_theme,
                default="colorblind",
                options=list(
                    "colorblind",
                    "classic",
                    "gray",
                    "Hollywood",
                    "Borkulo",
                    "TeamFortress",
                    "Reddit",
                    "Leuven",
                    "Fried"))
            private$..sna_plot_edge_color <- jmvcore::OptionList$new(
                "sna_plot_edge_color",
                sna_plot_edge_color,
                default="default",
                options=list(
                    "default",
                    "green",
                    "blue",
                    "red",
                    "orange",
                    "purple",
                    "gray",
                    "black"))
            private$..sna_plot_details <- jmvcore::OptionBool$new(
                "sna_plot_details",
                sna_plot_details,
                default=FALSE)
            private$..sna_plot_width <- jmvcore::OptionInteger$new(
                "sna_plot_width",
                sna_plot_width,
                default=600,
                min=300,
                max=1200)
            private$..sna_plot_height <- jmvcore::OptionInteger$new(
                "sna_plot_height",
                sna_plot_height,
                default=600,
                min=300,
                max=1200)
            private$..centrality_show_table <- jmvcore::OptionBool$new(
                "centrality_show_table",
                centrality_show_table,
                default=FALSE)
            private$..centrality_OutStrength <- jmvcore::OptionBool$new(
                "centrality_OutStrength",
                centrality_OutStrength,
                default=TRUE)
            private$..centrality_InStrength <- jmvcore::OptionBool$new(
                "centrality_InStrength",
                centrality_InStrength,
                default=TRUE)
            private$..centrality_Betweenness <- jmvcore::OptionBool$new(
                "centrality_Betweenness",
                centrality_Betweenness,
                default=TRUE)
            private$..centrality_BetweennessRSP <- jmvcore::OptionBool$new(
                "centrality_BetweennessRSP",
                centrality_BetweennessRSP,
                default=FALSE)
            private$..centrality_Closeness <- jmvcore::OptionBool$new(
                "centrality_Closeness",
                centrality_Closeness,
                default=FALSE)
            private$..centrality_ClosenessIn <- jmvcore::OptionBool$new(
                "centrality_ClosenessIn",
                centrality_ClosenessIn,
                default=FALSE)
            private$..centrality_ClosenessOut <- jmvcore::OptionBool$new(
                "centrality_ClosenessOut",
                centrality_ClosenessOut,
                default=FALSE)
            private$..centrality_Diffusion <- jmvcore::OptionBool$new(
                "centrality_Diffusion",
                centrality_Diffusion,
                default=FALSE)
            private$..centrality_Clustering <- jmvcore::OptionBool$new(
                "centrality_Clustering",
                centrality_Clustering,
                default=FALSE)
            private$..centrality_loops <- jmvcore::OptionBool$new(
                "centrality_loops",
                centrality_loops,
                default=FALSE)
            private$..centrality_normalize <- jmvcore::OptionBool$new(
                "centrality_normalize",
                centrality_normalize,
                default=FALSE)
            private$..community_show_table <- jmvcore::OptionBool$new(
                "community_show_table",
                community_show_table,
                default=FALSE)
            private$..community_walktrap <- jmvcore::OptionBool$new(
                "community_walktrap",
                community_walktrap,
                default=TRUE)
            private$..community_fast_greedy <- jmvcore::OptionBool$new(
                "community_fast_greedy",
                community_fast_greedy,
                default=TRUE)
            private$..community_label_prop <- jmvcore::OptionBool$new(
                "community_label_prop",
                community_label_prop,
                default=FALSE)
            private$..community_infomap <- jmvcore::OptionBool$new(
                "community_infomap",
                community_infomap,
                default=FALSE)
            private$..community_edge_betweenness <- jmvcore::OptionBool$new(
                "community_edge_betweenness",
                community_edge_betweenness,
                default=FALSE)
            private$..community_leading_eigen <- jmvcore::OptionBool$new(
                "community_leading_eigen",
                community_leading_eigen,
                default=FALSE)
            private$..community_spinglass <- jmvcore::OptionBool$new(
                "community_spinglass",
                community_spinglass,
                default=FALSE)
            private$..edge_betweenness_show_table <- jmvcore::OptionBool$new(
                "edge_betweenness_show_table",
                edge_betweenness_show_table,
                default=FALSE)
            private$..edge_betweenness_directed <- jmvcore::OptionBool$new(
                "edge_betweenness_directed",
                edge_betweenness_directed,
                default=TRUE)

            self$.addOption(private$..sna_from)
            self$.addOption(private$..sna_to)
            self$.addOption(private$..sna_weight)
            self$.addOption(private$..sna_group)
            self$.addOption(private$..sna_aggregate)
            self$.addOption(private$..sna_show_summary)
            self$.addOption(private$..sna_show_degree_plot)
            self$.addOption(private$..sna_show_plot)
            self$.addOption(private$..sna_plot_node_size_slider)
            self$.addOption(private$..sna_plot_edge_size_slider)
            self$.addOption(private$..sna_plot_show_node_labels)
            self$.addOption(private$..sna_plot_show_edge_labels)
            self$.addOption(private$..sna_plot_cut)
            self$.addOption(private$..sna_plot_min_value)
            self$.addOption(private$..sna_plot_edge_label_size)
            self$.addOption(private$..sna_plot_node_size)
            self$.addOption(private$..sna_plot_node_label_size)
            self$.addOption(private$..sna_plot_layout)
            self$.addOption(private$..sna_plot_repulsion)
            self$.addOption(private$..sna_plot_vsize)
            self$.addOption(private$..sna_plot_borders)
            self$.addOption(private$..sna_plot_border_width)
            self$.addOption(private$..sna_plot_asize)
            self$.addOption(private$..sna_plot_curve)
            self$.addOption(private$..sna_plot_curveAll)
            self$.addOption(private$..sna_plot_theme)
            self$.addOption(private$..sna_plot_edge_color)
            self$.addOption(private$..sna_plot_details)
            self$.addOption(private$..sna_plot_width)
            self$.addOption(private$..sna_plot_height)
            self$.addOption(private$..centrality_show_table)
            self$.addOption(private$..centrality_OutStrength)
            self$.addOption(private$..centrality_InStrength)
            self$.addOption(private$..centrality_Betweenness)
            self$.addOption(private$..centrality_BetweennessRSP)
            self$.addOption(private$..centrality_Closeness)
            self$.addOption(private$..centrality_ClosenessIn)
            self$.addOption(private$..centrality_ClosenessOut)
            self$.addOption(private$..centrality_Diffusion)
            self$.addOption(private$..centrality_Clustering)
            self$.addOption(private$..centrality_loops)
            self$.addOption(private$..centrality_normalize)
            self$.addOption(private$..community_show_table)
            self$.addOption(private$..community_walktrap)
            self$.addOption(private$..community_fast_greedy)
            self$.addOption(private$..community_label_prop)
            self$.addOption(private$..community_infomap)
            self$.addOption(private$..community_edge_betweenness)
            self$.addOption(private$..community_leading_eigen)
            self$.addOption(private$..community_spinglass)
            self$.addOption(private$..edge_betweenness_show_table)
            self$.addOption(private$..edge_betweenness_directed)
        }),
    active = list(
        sna_from = function() private$..sna_from$value,
        sna_to = function() private$..sna_to$value,
        sna_weight = function() private$..sna_weight$value,
        sna_group = function() private$..sna_group$value,
        sna_aggregate = function() private$..sna_aggregate$value,
        sna_show_summary = function() private$..sna_show_summary$value,
        sna_show_degree_plot = function() private$..sna_show_degree_plot$value,
        sna_show_plot = function() private$..sna_show_plot$value,
        sna_plot_node_size_slider = function() private$..sna_plot_node_size_slider$value,
        sna_plot_edge_size_slider = function() private$..sna_plot_edge_size_slider$value,
        sna_plot_show_node_labels = function() private$..sna_plot_show_node_labels$value,
        sna_plot_show_edge_labels = function() private$..sna_plot_show_edge_labels$value,
        sna_plot_cut = function() private$..sna_plot_cut$value,
        sna_plot_min_value = function() private$..sna_plot_min_value$value,
        sna_plot_edge_label_size = function() private$..sna_plot_edge_label_size$value,
        sna_plot_node_size = function() private$..sna_plot_node_size$value,
        sna_plot_node_label_size = function() private$..sna_plot_node_label_size$value,
        sna_plot_layout = function() private$..sna_plot_layout$value,
        sna_plot_repulsion = function() private$..sna_plot_repulsion$value,
        sna_plot_vsize = function() private$..sna_plot_vsize$value,
        sna_plot_borders = function() private$..sna_plot_borders$value,
        sna_plot_border_width = function() private$..sna_plot_border_width$value,
        sna_plot_asize = function() private$..sna_plot_asize$value,
        sna_plot_curve = function() private$..sna_plot_curve$value,
        sna_plot_curveAll = function() private$..sna_plot_curveAll$value,
        sna_plot_theme = function() private$..sna_plot_theme$value,
        sna_plot_edge_color = function() private$..sna_plot_edge_color$value,
        sna_plot_details = function() private$..sna_plot_details$value,
        sna_plot_width = function() private$..sna_plot_width$value,
        sna_plot_height = function() private$..sna_plot_height$value,
        centrality_show_table = function() private$..centrality_show_table$value,
        centrality_OutStrength = function() private$..centrality_OutStrength$value,
        centrality_InStrength = function() private$..centrality_InStrength$value,
        centrality_Betweenness = function() private$..centrality_Betweenness$value,
        centrality_BetweennessRSP = function() private$..centrality_BetweennessRSP$value,
        centrality_Closeness = function() private$..centrality_Closeness$value,
        centrality_ClosenessIn = function() private$..centrality_ClosenessIn$value,
        centrality_ClosenessOut = function() private$..centrality_ClosenessOut$value,
        centrality_Diffusion = function() private$..centrality_Diffusion$value,
        centrality_Clustering = function() private$..centrality_Clustering$value,
        centrality_loops = function() private$..centrality_loops$value,
        centrality_normalize = function() private$..centrality_normalize$value,
        community_show_table = function() private$..community_show_table$value,
        community_walktrap = function() private$..community_walktrap$value,
        community_fast_greedy = function() private$..community_fast_greedy$value,
        community_label_prop = function() private$..community_label_prop$value,
        community_infomap = function() private$..community_infomap$value,
        community_edge_betweenness = function() private$..community_edge_betweenness$value,
        community_leading_eigen = function() private$..community_leading_eigen$value,
        community_spinglass = function() private$..community_spinglass$value,
        edge_betweenness_show_table = function() private$..edge_betweenness_show_table$value,
        edge_betweenness_directed = function() private$..edge_betweenness_directed$value),
    private = list(
        ..sna_from = NA,
        ..sna_to = NA,
        ..sna_weight = NA,
        ..sna_group = NA,
        ..sna_aggregate = NA,
        ..sna_show_summary = NA,
        ..sna_show_degree_plot = NA,
        ..sna_show_plot = NA,
        ..sna_plot_node_size_slider = NA,
        ..sna_plot_edge_size_slider = NA,
        ..sna_plot_show_node_labels = NA,
        ..sna_plot_show_edge_labels = NA,
        ..sna_plot_cut = NA,
        ..sna_plot_min_value = NA,
        ..sna_plot_edge_label_size = NA,
        ..sna_plot_node_size = NA,
        ..sna_plot_node_label_size = NA,
        ..sna_plot_layout = NA,
        ..sna_plot_repulsion = NA,
        ..sna_plot_vsize = NA,
        ..sna_plot_borders = NA,
        ..sna_plot_border_width = NA,
        ..sna_plot_asize = NA,
        ..sna_plot_curve = NA,
        ..sna_plot_curveAll = NA,
        ..sna_plot_theme = NA,
        ..sna_plot_edge_color = NA,
        ..sna_plot_details = NA,
        ..sna_plot_width = NA,
        ..sna_plot_height = NA,
        ..centrality_show_table = NA,
        ..centrality_OutStrength = NA,
        ..centrality_InStrength = NA,
        ..centrality_Betweenness = NA,
        ..centrality_BetweennessRSP = NA,
        ..centrality_Closeness = NA,
        ..centrality_ClosenessIn = NA,
        ..centrality_ClosenessOut = NA,
        ..centrality_Diffusion = NA,
        ..centrality_Clustering = NA,
        ..centrality_loops = NA,
        ..centrality_normalize = NA,
        ..community_show_table = NA,
        ..community_walktrap = NA,
        ..community_fast_greedy = NA,
        ..community_label_prop = NA,
        ..community_infomap = NA,
        ..community_edge_betweenness = NA,
        ..community_leading_eigen = NA,
        ..community_spinglass = NA,
        ..edge_betweenness_show_table = NA,
        ..edge_betweenness_directed = NA)
)

SNAResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SNAResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        errorText = function() private$.items[["errorText"]],
        sna_plot = function() private$.items[["sna_plot"]],
        graphMetricsTitle = function() private$.items[["graphMetricsTitle"]],
        summaryTable = function() private$.items[["summaryTable"]],
        degree_plot = function() private$.items[["degree_plot"]],
        snaModelTitle = function() private$.items[["snaModelTitle"]],
        snaModelContent = function() private$.items[["snaModelContent"]],
        centralityTitle = function() private$.items[["centralityTitle"]],
        centralityTable = function() private$.items[["centralityTable"]],
        communityTitle = function() private$.items[["communityTitle"]],
        communityTable = function() private$.items[["communityTable"]],
        edgeBetweennessTitle = function() private$.items[["edgeBetweennessTitle"]],
        edgeBetweennessTable = function() private$.items[["edgeBetweennessTable"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Social Network Analysis",
                refs=list(
                    "JTNA",
                    "SNA"))
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="errorText",
                title="Error",
                visible=FALSE))
            self$add(jmvcore::Image$new(
                options=options,
                name="sna_plot",
                width=600,
                height=600,
                visible=FALSE,
                renderFun=".showSNAPlot",
                clearWith=list(
                    "sna_from",
                    "sna_to",
                    "sna_weight",
                    "sna_group",
                    "sna_aggregate",
                    "sna_plot_node_size_slider",
                    "sna_plot_edge_size_slider",
                    "sna_plot_show_node_labels",
                    "sna_plot_show_edge_labels",
                    "sna_plot_cut",
                    "sna_plot_min_value",
                    "sna_plot_edge_label_size",
                    "sna_plot_node_size",
                    "sna_plot_node_label_size",
                    "sna_plot_layout",
                    "sna_plot_repulsion",
                    "sna_plot_vsize",
                    "sna_plot_borders",
                    "sna_plot_border_width",
                    "sna_plot_asize",
                    "sna_plot_curve",
                    "sna_plot_curveAll",
                    "sna_plot_theme",
                    "sna_plot_edge_color",
                    "sna_plot_details",
                    "sna_plot_width",
                    "sna_plot_height")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="graphMetricsTitle",
                title="Graph Level Metrics",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="summaryTable",
                title="Network Summary",
                visible=FALSE,
                columns=list(
                    list(
                        `name`="metric", 
                        `title`="Metric", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="number")),
                clearWith=list(
                    "sna_from",
                    "sna_to",
                    "sna_weight",
                    "sna_group",
                    "sna_aggregate")))
            self$add(jmvcore::Image$new(
                options=options,
                name="degree_plot",
                title="Degree Distribution",
                width=500,
                height=400,
                visible=FALSE,
                renderFun=".showDegreePlot",
                clearWith=list(
                    "sna_from",
                    "sna_to",
                    "sna_weight",
                    "sna_group",
                    "sna_aggregate")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="snaModelTitle",
                title="Model",
                visible=FALSE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="snaModelContent",
                visible=FALSE,
                clearWith=list(
                    "sna_from",
                    "sna_to",
                    "sna_weight",
                    "sna_group",
                    "sna_aggregate")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="centralityTitle",
                title="Centrality",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="centralityTable",
                title="Centrality Measures",
                visible=FALSE,
                columns=list(
                    list(
                        `name`="state", 
                        `type`="text")),
                clearWith=list(
                    "sna_from",
                    "sna_to",
                    "sna_weight",
                    "sna_group",
                    "sna_aggregate",
                    "centrality_show_table",
                    "centrality_loops",
                    "centrality_normalize",
                    "centrality_OutStrength",
                    "centrality_InStrength",
                    "centrality_Betweenness",
                    "centrality_BetweennessRSP",
                    "centrality_Closeness",
                    "centrality_ClosenessIn",
                    "centrality_ClosenessOut",
                    "centrality_Diffusion",
                    "centrality_Clustering")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="communityTitle",
                title="Community Detection",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="communityTable",
                title="Community Assignments",
                visible=FALSE,
                columns=list(
                    list(
                        `name`="state", 
                        `title`="State", 
                        `type`="text")),
                clearWith=list(
                    "sna_from",
                    "sna_to",
                    "sna_weight",
                    "sna_group",
                    "sna_aggregate",
                    "community_show_table",
                    "community_walktrap",
                    "community_fast_greedy",
                    "community_label_prop",
                    "community_infomap",
                    "community_edge_betweenness",
                    "community_leading_eigen",
                    "community_spinglass")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="edgeBetweennessTitle",
                title="Edge Betweenness",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="edgeBetweennessTable",
                title="Edge Betweenness",
                visible=FALSE,
                columns=list(
                    list(
                        `name`="from", 
                        `title`="From", 
                        `type`="text"),
                    list(
                        `name`="to", 
                        `title`="To", 
                        `type`="text"),
                    list(
                        `name`="betweenness", 
                        `title`="Betweenness", 
                        `type`="number")),
                clearWith=list(
                    "sna_from",
                    "sna_to",
                    "sna_weight",
                    "sna_group",
                    "sna_aggregate",
                    "edge_betweenness_show_table",
                    "edge_betweenness_directed")))}))

SNABase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "SNABase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "JTNA",
                name = "SNA",
                version = c(1,12,0),
                options = options,
                results = SNAResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Social Network Analysis
#'
#' 
#' @param data .
#' @param sna_from The column containing the source node of each edge
#'   (required).
#' @param sna_to The column containing the target node of each edge
#'   (required).
#' @param sna_weight The column containing edge weights. If not provided,
#'   defaults to 1 for unweighted networks.
#' @param sna_group The column containing group labels. If provided, separate
#'   networks will be built and plotted for each group.
#' @param sna_aggregate .
#' @param sna_show_summary .
#' @param sna_show_degree_plot .
#' @param sna_show_plot .
#' @param sna_plot_node_size_slider .
#' @param sna_plot_edge_size_slider .
#' @param sna_plot_show_node_labels .
#' @param sna_plot_show_edge_labels .
#' @param sna_plot_cut .
#' @param sna_plot_min_value .
#' @param sna_plot_edge_label_size .
#' @param sna_plot_node_size .
#' @param sna_plot_node_label_size .
#' @param sna_plot_layout .
#' @param sna_plot_repulsion .
#' @param sna_plot_vsize .
#' @param sna_plot_borders .
#' @param sna_plot_border_width .
#' @param sna_plot_asize .
#' @param sna_plot_curve .
#' @param sna_plot_curveAll .
#' @param sna_plot_theme .
#' @param sna_plot_edge_color .
#' @param sna_plot_details .
#' @param sna_plot_width .
#' @param sna_plot_height .
#' @param centrality_show_table .
#' @param centrality_OutStrength .
#' @param centrality_InStrength .
#' @param centrality_Betweenness .
#' @param centrality_BetweennessRSP .
#' @param centrality_Closeness .
#' @param centrality_ClosenessIn .
#' @param centrality_ClosenessOut .
#' @param centrality_Diffusion .
#' @param centrality_Clustering .
#' @param centrality_loops .
#' @param centrality_normalize .
#' @param community_show_table .
#' @param community_walktrap .
#' @param community_fast_greedy .
#' @param community_label_prop .
#' @param community_infomap .
#' @param community_edge_betweenness .
#' @param community_leading_eigen .
#' @param community_spinglass .
#' @param edge_betweenness_show_table .
#' @param edge_betweenness_directed .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$errorText} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$sna_plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$graphMetricsTitle} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$summaryTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$degree_plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$snaModelTitle} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$snaModelContent} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$centralityTitle} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$centralityTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$communityTitle} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$communityTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$edgeBetweennessTitle} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$edgeBetweennessTable} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$summaryTable$asDF}
#'
#' \code{as.data.frame(results$summaryTable)}
#'
#' @export
SNA <- function(
    data,
    sna_from,
    sna_to,
    sna_weight,
    sna_group,
    sna_aggregate = "sum",
    sna_show_summary = TRUE,
    sna_show_degree_plot = FALSE,
    sna_show_plot = TRUE,
    sna_plot_node_size_slider = 8,
    sna_plot_edge_size_slider = 6,
    sna_plot_show_node_labels = FALSE,
    sna_plot_show_edge_labels = FALSE,
    sna_plot_cut = 0.1,
    sna_plot_min_value = 0.05,
    sna_plot_edge_label_size = 1,
    sna_plot_node_size = 1,
    sna_plot_node_label_size = 1,
    sna_plot_layout,
    sna_plot_repulsion = 1,
    sna_plot_vsize = 8,
    sna_plot_borders = TRUE,
    sna_plot_border_width = 1,
    sna_plot_asize = 2,
    sna_plot_curve = 0,
    sna_plot_curveAll = FALSE,
    sna_plot_theme = "colorblind",
    sna_plot_edge_color = "default",
    sna_plot_details = FALSE,
    sna_plot_width = 600,
    sna_plot_height = 600,
    centrality_show_table = FALSE,
    centrality_OutStrength = TRUE,
    centrality_InStrength = TRUE,
    centrality_Betweenness = TRUE,
    centrality_BetweennessRSP = FALSE,
    centrality_Closeness = FALSE,
    centrality_ClosenessIn = FALSE,
    centrality_ClosenessOut = FALSE,
    centrality_Diffusion = FALSE,
    centrality_Clustering = FALSE,
    centrality_loops = FALSE,
    centrality_normalize = FALSE,
    community_show_table = FALSE,
    community_walktrap = TRUE,
    community_fast_greedy = TRUE,
    community_label_prop = FALSE,
    community_infomap = FALSE,
    community_edge_betweenness = FALSE,
    community_leading_eigen = FALSE,
    community_spinglass = FALSE,
    edge_betweenness_show_table = FALSE,
    edge_betweenness_directed = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("SNA requires jmvcore to be installed (restart may be required)")

    if ( ! missing(sna_from)) sna_from <- jmvcore::resolveQuo(jmvcore::enquo(sna_from))
    if ( ! missing(sna_to)) sna_to <- jmvcore::resolveQuo(jmvcore::enquo(sna_to))
    if ( ! missing(sna_weight)) sna_weight <- jmvcore::resolveQuo(jmvcore::enquo(sna_weight))
    if ( ! missing(sna_group)) sna_group <- jmvcore::resolveQuo(jmvcore::enquo(sna_group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(sna_from), sna_from, NULL),
            `if`( ! missing(sna_to), sna_to, NULL),
            `if`( ! missing(sna_weight), sna_weight, NULL),
            `if`( ! missing(sna_group), sna_group, NULL))


    options <- SNAOptions$new(
        sna_from = sna_from,
        sna_to = sna_to,
        sna_weight = sna_weight,
        sna_group = sna_group,
        sna_aggregate = sna_aggregate,
        sna_show_summary = sna_show_summary,
        sna_show_degree_plot = sna_show_degree_plot,
        sna_show_plot = sna_show_plot,
        sna_plot_node_size_slider = sna_plot_node_size_slider,
        sna_plot_edge_size_slider = sna_plot_edge_size_slider,
        sna_plot_show_node_labels = sna_plot_show_node_labels,
        sna_plot_show_edge_labels = sna_plot_show_edge_labels,
        sna_plot_cut = sna_plot_cut,
        sna_plot_min_value = sna_plot_min_value,
        sna_plot_edge_label_size = sna_plot_edge_label_size,
        sna_plot_node_size = sna_plot_node_size,
        sna_plot_node_label_size = sna_plot_node_label_size,
        sna_plot_layout = sna_plot_layout,
        sna_plot_repulsion = sna_plot_repulsion,
        sna_plot_vsize = sna_plot_vsize,
        sna_plot_borders = sna_plot_borders,
        sna_plot_border_width = sna_plot_border_width,
        sna_plot_asize = sna_plot_asize,
        sna_plot_curve = sna_plot_curve,
        sna_plot_curveAll = sna_plot_curveAll,
        sna_plot_theme = sna_plot_theme,
        sna_plot_edge_color = sna_plot_edge_color,
        sna_plot_details = sna_plot_details,
        sna_plot_width = sna_plot_width,
        sna_plot_height = sna_plot_height,
        centrality_show_table = centrality_show_table,
        centrality_OutStrength = centrality_OutStrength,
        centrality_InStrength = centrality_InStrength,
        centrality_Betweenness = centrality_Betweenness,
        centrality_BetweennessRSP = centrality_BetweennessRSP,
        centrality_Closeness = centrality_Closeness,
        centrality_ClosenessIn = centrality_ClosenessIn,
        centrality_ClosenessOut = centrality_ClosenessOut,
        centrality_Diffusion = centrality_Diffusion,
        centrality_Clustering = centrality_Clustering,
        centrality_loops = centrality_loops,
        centrality_normalize = centrality_normalize,
        community_show_table = community_show_table,
        community_walktrap = community_walktrap,
        community_fast_greedy = community_fast_greedy,
        community_label_prop = community_label_prop,
        community_infomap = community_infomap,
        community_edge_betweenness = community_edge_betweenness,
        community_leading_eigen = community_leading_eigen,
        community_spinglass = community_spinglass,
        edge_betweenness_show_table = edge_betweenness_show_table,
        edge_betweenness_directed = edge_betweenness_directed)

    analysis <- SNAClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

