
# This file is automatically generated, you probably don't want to edit this

.jmvrefs <- list(
    `JTNA`=list(
        `type`="software", 
        `author`="Girault, D., Saqr, M., L\u00F3pez-Pernas, S., & Tikka, S.", 
        `year`=2025, 
        `title`="JTNA: A jamovi module for Transition Network Analysis", 
        `publisher`="GitHub", 
        `url`="https://github.com/sonsoleslp/JTNA"), 
    `TNA`=list(
        `type`="article", 
        `author`="Tikka, S., L\u00F3pez-Pernas, S., & Saqr, M.", 
        `year`=2025, 
        `title`="tna: An R Package for Transition Network Analysis", 
        `publisher`="Applied Psychological Measurement", 
        `url`="https://doi.org/10.1177/01466216251348840"), 
    `TNALAK`=list(
        `type`="article", 
        `author`="Saqr, M., L\u00F3pez-Pernas, S., T\u00F6rm\u00E4nen, T., Kaliisa, R., Misiejuk, K., & Tikka, S.", 
        `year`=2025, 
        `title`="Transition network analysis: A novel framework for modeling, visualizing, and identifying the temporal patterns of learners and learning processes", 
        `publisher`="Proceedings of the 15th International Learning Analytics and Knowledge Conference (pp. 351-361)", 
        `url`="https://doi.org/10.1145/3706468.3706513"))
