---
title: "Untitled"
output: html_document
date: "2025-06-28"
---



```{r}
library(dplyr)
library(tna)

source("/Users/mohammedsaqr/Documents/GitHub/JTNA1.2/Run.R")


data("group_regulation_long")
Twogroups <- group_regulation_long %>% filter(Course!="C")
Data <- prepare_data(Twogroups, actor = "Actor", action = "Action")
GroupS <- group_tna(Data, group="Course")
permutation_results <- permutation_test(GroupS)
#print the results table
print(permutation_results$`A vs. B`$edges$stats)



Onegroup <-  group_regulation_long %>% filter(Course=="C")
Data1 <- prepare_data(Onegroup, actor = "Actor", action = "Action")

Single <- tna(Data1)
Bootstrap_results <- bootstrap(Single)
print (Bootstrap_results$summary)


```

```{r}
library(tna)
data("group_regulation_long")
Threegroups <- group_regulation_long 
Data3 <- prepare_data(Threegroups, actor = "Actor", action = "Action")
Group3 <- group_tna(Data3, group="Course")

bootstrap_results3 <- bootstrap(Group3)

plot(bootstrap_results3)

permutation_results3$`A vs. B`
permutation_results3$`A vs. C`
permutation_results3$`B vs. C`


Data3 <- prepare_data(Threegroups, actor = "Actor", action = "Action")
Group3 <- group_tna(Data3, group="Course")
Bootstrap_results3 <- bootstrap(Group3)
print (Bootstrap_results3$A)
print (Bootstrap_results3$B)
print (Bootstrap_results3$C)


```


```{r}
layout (t(1:4))
data("group_regulation_long")
Singledata <- group_regulation_long %>% filter(Course=="C")
Data1 <- prepare_data(Singledata, actor = "Actor", action = "Action")

Single <- tna(Data1)
Cliques = cliques(Single)
plot(Cliques, ask = FALSE)

```

```{r}

Edgebetweeness <- betweenness_network(Single)
# The table is a square matrix 
print(Edgebetweeness$weights)
  


matrix_to_from_to_value <- function(your_matrix) {
  # Ensure the matrix has dimnames, or create generic ones if missing
  if (is.null(rownames(your_matrix))) {
    rownames(your_matrix) <- paste0("Row", 1:nrow(your_matrix))
  }
  if (is.null(colnames(your_matrix))) {
    colnames(your_matrix) <- paste0("Col", 1:ncol(your_matrix))
  }

  # Convert the matrix to a table object, then to a data frame,
  # and finally set the column names. This is a very concise
  # way to achieve the desired format in base R.
  df <- setNames(as.data.frame(as.table(your_matrix)), c("from", "to", "value"))
  return(df)
}


matrix_to_from_to_value (Edgebetweeness$weights)


Com <- communities(Single)
print(Com$assignments)

```


```{r}

BS <- bootstrap(Single)

plot()

```











